### ISSUE TITLE
xlxs workbook with column totals

### ISSUE THREAD

**Issue by brett39** [ggreen86/XLSX-Workbook-Class#10]
Hi Greg,

Not an issue but just some code that others may find useful. I have been using your routine in some of our local programs to export details from a grid to a working XLSX format spreadsheet and have found it to be a fantastic tool. 

In our own locally developed FoxPro programs we have the ability to set automatic column totals 'on' for all the entries in the grid that are numeric/currency/integers etc. When we export the contents of the grid to XLSX, it is handy to be able to have those same totals appear in the resulting spreadsheet. 

I have updated the code in our local copy of your class in the 'savegridtoworkbook()' method (see below towards the end of the pasted code below).

The code will automatically build up a '=sum(x2:x99:)' type formula and place it into the matching cell at the end of the spreadsheet using the same 'style' as the normal values in the spreadsheet except it will put a double line top border in the total cell. The method is also passed the 'tlsum' parameter which controls whether the totals are to be built.

Anyway, others may find it useful.

LPARAMETERS togrid, txwb, tlfreeze, tlsavewb, tcsheetname, tlinclhiddencols, tlsum
LOCAL lcalias, lncol, lnwb, lnsh, lnrow, lcfield, loreturn, locolumn, lnstyle, lncolcount
LOCAL ARRAY larowcount[1], lacolorder[1]
loreturn = CREATEOBJECT("Empty")
ADDPROPERTY(loreturn, "Workbook",  0)
ADDPROPERTY(loreturn, "Sheet", 0)
DO CASE
CASE PCOUNT() = 0
	RETURN loreturn

CASE PCOUNT() = 1
	RETURN loreturn

CASE PCOUNT() = 2
	tlfreeze     = true
	tlsavewb     = true
	tcsheetname  = THIS.derivesheetname(txwb)
	tlinclhiddencols = true
	tlsum = true

CASE PCOUNT() = 3
	tlsavewb     = true
	tcsheetname  = THIS.derivesheetname(txwb)
	tlinclhiddencols = true
	tlsum = true

CASE PCOUNT() = 4
	tcsheetname  = THIS.derivesheetname(txwb)
	tlinclhiddencols = true
	tlsum = true

CASE PCOUNT() = 5
	tlinclhiddencols = true
	tlsum = true

CASE PCOUNT() = 6
	tlsum = tlsum

ENDCASE

IF VARTYPE(tcsheetname) != 'C' .OR. EMPTY(tcsheetname)
	tcsheetname = THIS.derivesheetname(txwb)
ENDIF
IF VARTYPE(togrid) != "O" .AND. PEMSTATUS(togrid, "BaseClass", 5) .AND. LOWER(togrid.BASECLASS) != "grid"
	RETURN loreturn
ENDIF
DO CASE
CASE VARTYPE(txwb) = "C"
	lnwb = THIS.createworkbook(txwb)
	IF lnwb = 0
		lnwb = THIS.getworkbook(txwb)
	ENDIF

CASE VARTYPE(txwb) = "N"
	IF SEEK(BINTOC(txwb), "xl_workbooks", "workbook")
		lnwb = txwb
	ELSE
		RETURN loreturn
	ENDIF

OTHERWISE
	RETURN loreturn
ENDCASE
IF lnwb > 0
	lnsh = THIS.addsheet(lnwb, tcsheetname)
	IF lnsh > 0
		lcalias = JUSTSTEM(togrid.RECORDSOURCE)

*-*		Get the record count and display a status window
		SELECT COUNT(*) FROM &lcalias INTO ARRAY larowcount
		RAISEEVENT(THIS, "OnShowStatusMessage", 3, 0, larowcount[1])

*-*		Get the number of columns to process and
*-*		Get the column output order based on grid display order                       && Change requested by Matt Slay to output by grid display order and visible setting
		IF tlinclhiddencols
			lncolcount = togrid.COLUMNCOUNT
			DIMENSION lacolorder[lnColCount, 2]
			FOR lncol=1 TO togrid.COLUMNCOUNT
				lacolorder[lnCol, 1] = togrid.COLUMNS(lncol).COLUMNORDER              && Grid display order
				lacolorder[lnCol, 2] = lncol                                          && Column property order
			ENDFOR
		ELSE
			lncolcount = 0
			FOR lncol=1 TO togrid.COLUMNCOUNT
				IF togrid.COLUMNS(lncol).VISIBLE
					lncolcount = lncolcount + 1
					DIMENSION lacolorder[lnColCount, 2]
					lacolorder[lnColCount, 1] = togrid.COLUMNS(lncol).COLUMNORDER     && Grid display order
					lacolorder[lnColCount, 2] = lncol                                 && Column property order
				ENDIF
			ENDFOR
		ENDIF
		IF lncolcount = 0
			RETURN false
		ENDIF
		ASORT(lacolorder)

*-*		Add the header row if defined and set the column widths; get the column font info
		IF togrid.HEADERHEIGHT > 0                                                    && Change recommendation by Doug Hennig (if no headers, start in first row)
			lnrow = 1
			FOR lncol=1 TO lncolcount
				locolumn = togrid.COLUMNS(lacolorder[lnCol, 2])
				THIS.setcellvalue(lnwb, lnsh, 1, lncol, locolumn.header1.CAPTION)
				THIS.setcolumnwidth(lnwb, lnsh, lncol, THIS.convertpixelstoexcelunits(locolumn.WIDTH))
			ENDFOR
		ELSE
			lnrow = 0
			FOR lncol=1 TO lncolcount
				locolumn = togrid.COLUMNS(lacolorder[lnCol, 2])
				THIS.setcolumnwidth(lnwb, lnsh, lncol, THIS.convertpixelstoexcelunits(locolumn.WIDTH))
			ENDFOR
		ENDIF

*-*		Add the cell data values
		SELECT &lcalias
		SCAN
			lnrow = lnrow + 1
			RAISEEVENT(THIS, "OnShowStatusMessage", 3, lnrow)
			FOR lncol=1 TO lncolcount
				locolumn = togrid.COLUMNS(lacolorder[lnCol, 2])
				lcfield  = locolumn.CONTROLSOURCE
				THIS.setcellvalue(lnwb, lnsh, lnrow, lncol, &lcfield)
			ENDFOR
		ENDSCAN

*-*		Set the cell style formatting
		FOR lncol=1 TO lncolcount
			locolumn = togrid.COLUMNS(lacolorder[lnCol, 2])
			lnstyle  = THIS.createformatstyle(lnwb)
			IF THIS.defaultfont != locolumn.FONTNAME .OR. THIS.defaultfontsize != locolumn.FONTSIZE   && Change recommended by Doug Hennig; 2017-06-12
				THIS.addstylefont(lnwb, lnstyle, locolumn.FONTNAME, locolumn.FONTSIZE)
			ELSE
				THIS.addstylefont(lnwb, lnstyle, THIS.defaultfont, THIS.defaultfontsize)
			ENDIF
			THIS.setcellstylerange(lnwb, lnsh, 1, lncol, larowcount[1]+1, lncol, lnstyle)
		ENDFOR

*-*		Freeze the first row if specified
		IF tlfreeze
			THIS.freezepanes(lnwb, lnsh, 1, 0)
		ENDIF
*
*************************************************************************************************
*************************************************************************************************
*************************************************************************************************
*
*	bch added 8.11.2017 To add in a total for the numeric type columns. Also added code for tlsum flag setting.
*
		IF tlsum
			FOR lncol = 1 TO lncolcount
				lcdatatype = THIS.getcelldatatype(lnwb, lnsh, 2, lncol)
				IF INLIST(lcdatatype, data_type_currency, data_type_float, data_type_int)
					lccolumn = THIS.columnindextoascii(lncol)
					THIS.setcellformula(lnwb, lnsh, lnrow + 2, lncol, "=SUM(" + lccolumn + "2:" + lccolumn + ALLTRIM(STR(lnrow))+")")
					lnstylecell = THIS.getcellstyle(lnwb, lnsh, lnrow, lncol)
					THIS.setcellstyle(lnwb, lnsh, lnrow + 2, lncol, lnstylecell)
					THIS.setcellborder(lnwb, lnsh, lnrow + 2, lncol, border_top, border_style_double)
				ENDIF
			ENDFOR
		ENDIF
*
*************************************************************************************************
*************************************************************************************************
*************************************************************************************************
		RAISEEVENT(THIS, "OnShowStatusMessage", 3, -1)
		IF tlsavewb
			THIS.saveworkbook(lnwb)
		ENDIF
		loreturn.SHEET    = lnsh
		loreturn.workbook = lnwb
	ENDIF
ENDIF
RETURN loreturn

**Comment by ggreen86** [comment]
Brett--


Thank you for sharing the below code; I will certainly add it to the class and make it available to all.

Greg

________________________________

**Comment by brett39** [comment]
Hi Greg,

 

Firstly, congratulations on developing such a great routine. Must have taken quite a bit of time and effort. I have learnt a lot more about fox pro from just going through your code and it has really helped with some of our local development. 

 

A couple of things.

 

I noticed a typo error in my code.

 

CASE PCOUNT() = 6
tlsum = tlsum

should be

 

CASE PCOUNT() = 6
tlsum = true

Also, it may be that the ‘totals’ code could go into some of the other methods such as 'savegridtoworkbookex()’. I must admit I haven’t checked the other methods that closely as I was able to do what I needed within 'savegridtoworkbook()’.

 

I have also used the savetabletoworkbook/ex routines but have had some issues with large tables that have a high number of fields. I get an error as per the following. The table I am trying to export has over 56,000 records and over 150 fields. It looks like it is trying to convert the text file that is built up that holds the data and the styles etc. If I ‘ignore’ the error message, the data does load.

 

 

 

 

 

 

 

 

If you were happy with our service today, please click here <https://tinyurl.com/yantkxnm>  to add a review.

Kind regards,

 

Brett Hudson

Help Desk Manager

 

 

 

Redgum Software & Support

Yellow Goanna Pty Ltd

Suite 9, 469 King Street

West Melbourne VIC 3003

Ph: +61 3 9563-0350 | Fax: +61 3 9563-0348

www.redgumsoft.com.au <http://www.redgumsoft.com.au/> 

ABN: 38 165 809 889

 

This transmission is intended for the addressee only. If you have received this

transmission in error, please delete it and notify the sender. Thank you.

**Comment by ggreen86** [comment]
Brett--


Thank you for your congrats.  The class has been a while in the writing...  I am looking into how to determine which columns to sum -- not all columns may be desired.  As for the error that you are getting -- can you send me the XLSX file that is generated?  I would like to try to determine the cause of the error.


Greg

________________________________

**Comment by ggreen86** [comment]
Brett--


BTW - I noticed in your code use the following:


ALLTRIM(STR(lnrow))


This can be simplified to:


TRANSFORM(lnRow)


Greg

________________________________

**Comment by brett39** [comment]
Hi Greg,

 

I will send through the VFP table I am loading up and also the spreadsheet that is created if I select the IGNORE option at the error.

 

It may come across via a couple of emails because of the file size limitations with the email system. 

 

If you were happy with our service today, please click here <https://tinyurl.com/yantkxnm>  to add a review.

Kind regards,

 

Brett Hudson

Help Desk Manager

 

 

 

Redgum Software & Support

Yellow Goanna Pty Ltd

Suite 9, 469 King Street

West Melbourne VIC 3003

Ph: +61 3 9563-0350 | Fax: +61 3 9563-0348

www.redgumsoft.com.au <http://www.redgumsoft.com.au/> 

ABN: 38 165 809 889

 

This transmission is intended for the addressee only. If you have received this

transmission in error, please delete it and notify the sender. Thank you.

**Comment by brett39** [comment]
Part 1 of input table INV

 

 

 

If you were happy with our service today, please click here <https://tinyurl.com/yantkxnm>  to add a review.

Kind regards,

 

Brett Hudson

Help Desk Manager

 

 

 

Redgum Software & Support

Yellow Goanna Pty Ltd

Suite 9, 469 King Street

West Melbourne VIC 3003

Ph: +61 3 9563-0350 | Fax: +61 3 9563-0348

www.redgumsoft.com.au <http://www.redgumsoft.com.au/> 

ABN: 38 165 809 889

 

This transmission is intended for the addressee only. If you have received this

transmission in error, please delete it and notify the sender. Thank you.

**Comment by brett39** [comment]
Part 3 of input file.

 

 

 

If you were happy with our service today, please click here <https://tinyurl.com/yantkxnm>  to add a review.

Kind regards,

 

Brett Hudson

Help Desk Manager

 

 

 

Redgum Software & Support

Yellow Goanna Pty Ltd

Suite 9, 469 King Street

West Melbourne VIC 3003

Ph: +61 3 9563-0350 | Fax: +61 3 9563-0348

www.redgumsoft.com.au <http://www.redgumsoft.com.au/> 

ABN: 38 165 809 889

 

This transmission is intended for the addressee only. If you have received this

transmission in error, please delete it and notify the sender. Thank you.

**Comment by ggreen86** [comment]
No attachment sent...


________________________________

**Comment by ggreen86** [comment]
No attachment sent...


________________________________

**Comment by brett39** [comment]
Get the error, click ignore, the process keeps going and creates the spreadsheet.

 

The spreadsheet zipped file size is 13,880kb and won’t get through the email system. I don’t know if there is some other way that I can get it to you.

 

 

 

 

If you were happy with our service today, please click here <https://tinyurl.com/yantkxnm>  to add a review.

Kind regards,

 

Brett Hudson

Help Desk Manager

 

 

 

Redgum Software & Support

Yellow Goanna Pty Ltd

Suite 9, 469 King Street

West Melbourne VIC 3003

Ph: +61 3 9563-0350 | Fax: +61 3 9563-0348

www.redgumsoft.com.au <http://www.redgumsoft.com.au/> 

ABN: 38 165 809 889

 

This transmission is intended for the addressee only. If you have received this

transmission in error, please delete it and notify the sender. Thank you.

**Comment by brett39** [comment]
Hi Greg,

 

They are getting bounced by the mail system as it is saying that it is full.

 

Is there some other way of getting you the data other than via email?

 

If you were happy with our service today, please click here <https://tinyurl.com/yantkxnm>  to add a review.

Kind regards,

 

Brett Hudson

Help Desk Manager

 

 

 

Redgum Software & Support

Yellow Goanna Pty Ltd

Suite 9, 469 King Street

West Melbourne VIC 3003

Ph: +61 3 9563-0350 | Fax: +61 3 9563-0348

www.redgumsoft.com.au <http://www.redgumsoft.com.au/> 

ABN: 38 165 809 889

 

This transmission is intended for the addressee only. If you have received this

transmission in error, please delete it and notify the sender. Thank you.

**Comment by ggreen86** [comment]
Do you have a dropbox account that you can post the file to?  BTW - a XLSX file is actually a ZIP file with just the extension renamed.


________________________________

**Comment by brett39** [comment]
Copying up now. Will give you the details when done.

 

If you were happy with our service today, please click here <https://tinyurl.com/yantkxnm>  to add a review.

Kind regards,

 

Brett Hudson

Help Desk Manager

 

 

 

Redgum Software & Support

Yellow Goanna Pty Ltd

Suite 9, 469 King Street

West Melbourne VIC 3003

Ph: +61 3 9563-0350 | Fax: +61 3 9563-0348

www.redgumsoft.com.au <http://www.redgumsoft.com.au/> 

ABN: 38 165 809 889

 

This transmission is intended for the addressee only. If you have received this

transmission in error, please delete it and notify the sender. Thank you.

**Comment by ggreen86** [comment]
Brett--


I am not sure of adding your code to the class.  The intent is to keep it generic as possible.  Right now I am not sure how to allow for selected columns to be summed as a total.  In your case you are summing all numeric columns; not everyone might want that behavior.  I am considering how to possibly add...


But in the mean time, I would suggest not changing my class -- keep it the same as you downloaded it.  This way you don't have to update the code since you modified it each time there is a new release of my class.  Instead, create a new sub-class of the VFPxWorkbook class.  Now you can add your own version of the SaveGridToWorkbook() that calls the one in my class.  You might call your method "SaveGridToWorkbookTotals()".


In your SaveGridToWorkbookTotals() method:


LPARAMETERS toGrid, txWB, tlFreeze, tlSaveWB, tcSheetName, tlInclHiddenCols, tlSum

LOCAL loReturn

loReturn = this.SaveGridToWorkbook(toGrid, txWB, tlFreeze, False, tcSheetName, tlInclHiddenCols)   && we are passing False for the save workbook

IF loReturn.Workbook > 0

    IF tlSum

        lncolcount = this.GetMaxColumnNumber(loReturn.Workbook, loReturn.Sheet)

        lnrow = this.GetLastRowNumber(loReturn.WorkbookloReturn.Sheet)

        FOR lncol = 1 TO lncolcount
            lcdatatype = THIS.getcelldatatype(loReturn.Workbook, loReturn.Sheet, 2, lncol)
            IF INLIST(lcdatatype, data_type_currency, data_type_float, data_type_int)
                lccolumn = THIS.columnindextoascii(lncol)
                THIS.setcellformula(loReturn.Workbook, loReturn.Sheet, lnrow + 2, lncol, "=SUM(" + lccolumn + "2:" + lccolumn + TRANSFORM(lnrow) + ")")
                lnstylecell = THIS.getcellstyle(loReturn.Workbook, loReturn.Sheet, lnrow, lncol)
                THIS.setcellstyle(loReturn.Workbook, loReturn.Sheet, lnrow + 2, lncol, lnstylecell)
                THIS.setcellborder(loReturn.Workbook, loReturn.Sheet, lnrow + 2, lncol, border_top, border_style_double)
            ENDIF
        ENDFOR
    ENDIF
    IF tlSaveWB
        this.SaveWorkbook(loReturn.Workbook)
    ENDIF
ENDIF

RETURN loReturn


I think I got all your code variables changed to account for return value.  This way your code does the work of adding the column sums and it keeps you from changing the code in my class.  Now all you have to do is update my class each time and your code still works.


Greg

________________________________

**Comment by brett39** [comment]
Thanks Greg,

 

Yes. My amendments will total any and all numeric fields. I do understand that not all users may to total all numerics. 

 

I have copied up the files I am using with the class but hetting the file size error on to drop box and I have set up a shared folder with access given to the email account of XLXS-Workbook-Class@noreply.github.com so hopefully this gives you access. I haven’t used Drop box much (obviously) so I’m not sure on how to best give you access.

 

 

 

If you were happy with our service today, please click here <https://tinyurl.com/yantkxnm>  to add a review.

Kind regards,

 

Brett Hudson

Help Desk Manager

 

 

 

Redgum Software & Support

Yellow Goanna Pty Ltd

Suite 9, 469 King Street

West Melbourne VIC 3003

Ph: +61 3 9563-0350 | Fax: +61 3 9563-0348

www.redgumsoft.com.au <http://www.redgumsoft.com.au/> 

ABN: 38 165 809 889

 

This transmission is intended for the addressee only. If you have received this

transmission in error, please delete it and notify the sender. Thank you.

**Comment by ggreen86** [comment]
You should be able to access the file in the Windows File Explorer and see that it is synchronized with DropBox.  Then right-click on the file and select the public link to share and send that to me.   This message is going through GitHub and you might not want to send the link to me via there.  Please send directly to me at anduril58 at hotmail dot com.

Greg

________________________________
