### ISSUE TITLE
Problem at runtime

### ISSUE THREAD

**Issue by mrrosemberg** [ggreen86/XLSX-Workbook-Class#101]
class working fine in VFP9 SP2. Running the executable fails on the method loExcel.SaveTableToWorkbookEx
Returns .f.

not sure how to use BINDEVENTS with the loExcel object

Here's the code:

LOCAL loExcel, lcTable
myfile = mypath  + par_file                
SET SAFETY OFF
lcTable = 'reportCursor'
WAIT WINDOW 'Exporting to Excel' NOWAIT 
loExcel = NEWOBJECT("VFPxWorkbookXLSX", "VFPxWorkbookXLSX.vcx") && it's in the PATH
* Exports a table lcTable to xlsx myfile, worksheet name Iconsistency and light blue style 13
IF NOT loExcel.SaveTableToWorkbookEx(lcTable, myfile, .NULL., .T., 'Iconsistency', 1, 1, .T., TABLE_STYLE_LIGHT13) 
    this.lastError = 'Error creating file '+myfile && this property handles the class errors.
    RETURN .f.
ENDIF
WAIT CLEAR 
RETURN .t.

**Comment by mrrosemberg** [comment]
I managed to get the error:
ErrorLevelID 12
Exception Message: CreaExcelFile - Failed to add contents to Zip file
Member NAMESPACE does not evaluate to an object
As I mentioned, this only happens in runtime. The xlsx is generated correctly when running from VFP9.
Any help is appreciated.

**Comment by ggreen86** [comment]
Hello

I am not sure how to correct this.  The error is being given by the Windows operating system and not by my class.  What is the OS version number?  You could try to override my method by subclassing the workbook class and using an alternative way to create the zip file such as Craig Boyd’s VFPCompression class.

Greg

**Comment by ggreen86** [comment]
This is an issue with Windows and cannot be solved by this class; closing issue.
