### ISSUE TITLE
WriteSheetXMLS - Sets All Columns to Hidden rather than just the single column.

### ISSUE THREAD

**Issue by rawilliamsjr** [ggreen86/XLSX-Workbook-Class#103]
DO CASE
					CASE lnColWidth > -1.00 .AND. xl_temp.collevel = 0 .AND. **_xl_columns_**.hidden = 0
						FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" customWidth="1"')

					CASE lnColWidth > -1.00 .AND. xl_temp.collevel = 0 .AND. **_xl_columns_**.hidden = 1
						FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" hidden="1" customWidth="1"')

					CASE lnColWidth = -1.00 .AND. xl_temp.collevel > 0
						FWRITE(lhFile, ' outlineLevel="' + TRANSFORM(xl_temp.collevel) + '"/>')

					CASE lnColWidth > -1.00 .AND. xl_temp.collevel > 0
						FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" customWidth="1" outlineLevel="' + TRANSFORM(xl_temp.collevel) + '"')
				ENDCASE

Should be

				DO CASE
					CASE lnColWidth > -1.00 .AND. xl_temp.collevel = 0 .AND. **xl_temp**.hidden = 0
						FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" customWidth="1"')

					CASE lnColWidth > -1.00 .AND. xl_temp.collevel = 0 .AND. **xl_temp**.hidden = 1
						FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" hidden="1" customWidth="1"')

					CASE lnColWidth = -1.00 .AND. xl_temp.collevel > 0
						FWRITE(lhFile, ' outlineLevel="' + TRANSFORM(xl_temp.collevel) + '"/>')

					CASE lnColWidth > -1.00 .AND. xl_temp.collevel > 0
						FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" customWidth="1" outlineLevel="' + TRANSFORM(xl_temp.collevel) + '"')
				ENDCASE

**Comment by ggreen86** [comment]
Rob—

Thank you for this correction.  I have applied it to my code base.  I have several other issues to look at (but have limited time right now) and resolve.  I will then upload as a new release.

Greg

From: Rob Williams ***@***.***>
Sent: Wednesday, December 20, 2023 6:34 PM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] WriteSheetXMLS - Sets All Columns to Hidden rather than just the single column. (Issue #103)


                       DO CASE

                               CASE lnColWidth > -1.00 .AND. xl_temp.collevel = 0 .AND. **_xl_columns_**.hidden = 0

                                      FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" customWidth="1"')



                               CASE lnColWidth > -1.00 .AND. xl_temp.collevel = 0 .AND. **_xl_columns_**.hidden = 1

                                      FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" hidden="1" customWidth="1"')



                               CASE lnColWidth = -1.00 .AND. xl_temp.collevel > 0

                                      FWRITE(lhFile, ' outlineLevel="' + TRANSFORM(xl_temp.collevel) + '"/>')



                               CASE lnColWidth > -1.00 .AND. xl_temp.collevel > 0

                                      FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" customWidth="1" outlineLevel="' + TRANSFORM(xl_temp.collevel) + '"')

                       ENDCASE

Should be

                       DO CASE

                               CASE lnColWidth > -1.00 .AND. xl_temp.collevel = 0 .AND. **xl_temp**.hidden = 0

                                      FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" customWidth="1"')



                               CASE lnColWidth > -1.00 .AND. xl_temp.collevel = 0 .AND. **xl_temp**.hidden = 1

                                      FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" hidden="1" customWidth="1"')



                               CASE lnColWidth = -1.00 .AND. xl_temp.collevel > 0

                                      FWRITE(lhFile, ' outlineLevel="' + TRANSFORM(xl_temp.collevel) + '"/>')



                               CASE lnColWidth > -1.00 .AND. xl_temp.collevel > 0

                                      FWRITE(lhFile, ' width="' + TRANSFORM(lnColWidth) + '" customWidth="1" outlineLevel="' + TRANSFORM(xl_temp.collevel) + '"')

                       ENDCASE

**Comment by ggreen86** [comment]
Closing this issue; it is corrected in Release 40 (to be uploaded soon).
