### ISSUE TITLE
how work cursor 

### ISSUE THREAD

**Issue by flexsoluciones** [ggreen86/XLSX-Workbook-Class#106]
Hello i need example work cursor vfp thanks

**Comment by jhernancanom** [comment]
Colleague:
Just download and see(run) the examples.
![image](https://github.com/ggreen86/XLSX-Workbook-Class/assets/5818845/f839b2df-f0ba-4270-a1a6-9f7dc9a48428)

**Comment by flexsoluciones** [comment]
thanks and autofilter columns cursor to excel exist ?

**Comment by ggreen86** [comment]
Thank you for the help in directing the question to the answer 😊

Greg

**Comment by ggreen86** [comment]
Run the program “excelxlsxtest.prg”.  This will create a spreadsheet showing many of the features of the class.  This is from the class method “Demo()”.

**Comment by flexsoluciones** [comment]
error thisform.clsVFPxWorkbookXLSX.SaveTabletoWorkbookEx("reportexls", lcExcel,  .NULL., .T., "Employees", 1, 1, TABLE_STYLE_LIGHT13)
no exist TABLE_STYLE_LIGHT13

**Comment by flexsoluciones** [comment]
in demo prg error
![image](https://github.com/ggreen86/XLSX-Workbook-Class/assets/97065807/b7d1a07f-c894-4d59-a83c-898c096cab9d)

**Comment by ggreen86** [comment]
Unfortunately the screen shot does not show any helpful information.  I can run the same program without any errors on my system.

Greg

**Comment by ggreen86** [comment]
That define is in an include file – make sure it is in your path.

**Comment by ggreen86** [comment]
No information provided to duplicate error. Closing Issue.
