### ISSUE TITLE
WorkbookSaveAs - error when attempt to open the new workbook

### ISSUE THREAD

**Issue by rawilliamsjr** [ggreen86/XLSX-Workbook-Class#109]
When running the following code

Do system.app
lcAppendToFileName = "[Availability_Template.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/14089310/Availability_Template.xlsx)"
lnWb = goExcel.OpenXLSXWorkBook(lcAppendToFileName)
goExcel.SaveWorkbookAs(lnWb, "[Availability.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/14089367/Availability.xlsx)")

Attempted to open the new workbook in Excel and received the following message.

![image](https://github.com/ggreen86/XLSX-Workbook-Class/assets/61763592/de3bc583-152d-4752-bba9-888f88aae61b)

Click Yes

![image](https://github.com/ggreen86/XLSX-Workbook-Class/assets/61763592/ccf50a59-9dad-4b9b-8f4d-339112cba232)

**Comment by rawilliamsjr** [comment]
Do you have an ETA for this correction? We are in the middle of a large project and this issue is holding us up from completing the project.

**Comment by DougHennig** [comment]
@rawilliamsjr Just a reminder that this isn't a commercial product but volunteer work.

**Comment by ggreen86** [comment]
Unfortunately no I do not have an ETA.  I have not had the time to work on this issue in the past few weeks due to my regular job requirements.

**Comment by rawilliamsjr** [comment]
I apologize for the brevity of my previous message. I did not intend to cause any offense. I will ensure that our ongoing project runs smoothly until you address the reported issues. Additionally, I wanted to express my gratitude for the class you provided, as it has enabled us to implement a variety of new features in our applications. Thank you.

**Comment by ggreen86** [comment]
Rob-

No problem nor any offense taken.  I have had some time to work on this issue.  I have solved the insert row and correctly adjusting the merged cells.  However, I am having problems in the images that are part of the workbook and still debugging this problem which causes Excel to reject the graphic definitions.

Greg

**Comment by rawilliamsjr** [comment]
Greg, 

Thank you for the update.

**Comment by ggreen86** [comment]
Hello--

I now have a solution for the graphic problem.  Please try the attached version (preliminary R41) of the class library and let me know it is working for you.  If you can try on multiple spreadsheets that will be great.  BTW -- you have two Facebook images in the spreadsheet that you gave me (one directly on top of the other).

I will be uploading R41 as beta when I can update the documentation.

Greg

[WorkbookXLSX R41 Beta 1.zip](https://github.com/ggreen86/XLSX-Workbook-Class/files/14251505/WorkbookXLSX.R41.Beta.1.zip)

**Comment by ggreen86** [comment]
Hello--

I still have issues with the InsertRow for handling merged rows/columns (probably same with DeleteRow, InsertColumn, etc.).  I will continue with debugging the problem as I have the time.

Greg

**Comment by ggreen86** [comment]
Hello--

I believe I have now corrected the issues with the InsertRow, InsertColumn, DeleteRow, and DeleteColumn methods when there are merged cells that are affected by the change (similar to how Excel would handle the change).  I am attaching Release 41 Beta 2 for you to test with. Please let me know if you have any issues.

I am still working on the InsertCell and DeleteCell methods.

Greg

[WorkbookXLSX R41 Beta 2.zip](https://github.com/ggreen86/XLSX-Workbook-Class/files/14272906/WorkbookXLSX.R41.Beta.2.zip)

**Comment by rawilliamsjr** [comment]
After using WorkbookXLSX beta 2, the images no longer present an error when opening the newly created workbook, and the InsertRow method works as expected in my case.

Thank you for your time, effort, and communication.

**Comment by ggreen86** [comment]
Rob—

Thank you for the feedback.  I am glad this is now working for your project.  I am still working on the InsertCell and DeleteCell methods and will release these changes to the general community when I have these completed and tested by me as a beta release.

Greg

**Comment by rawilliamsjr** [comment]
I found an issue with the Beta 2.

Method GetLastRowNumber returned an error that CellRow was not found.

**Comment by rawilliamsjr** [comment]
While testing the Beta saving the Workbook with no changes is setting all cells as Locked. I have included my basic test code the Excel_Availability_Template.xlsx saving as Excel_Availability.xlsx with no modifications.


PUBLIC goXLSX

DO C:\GrowPoint\SYSTEM.APP

goXLSX = NEWOBJECT('vfpxworkbookxlsx', 'C:\Users\RobW\Downloads\WorkbookXSLX_Beta\vfpxworkbookxlsx.vcx')

lnWb = goXLSX.OpenXLSXWorkBook("C:\GrowPoint\Excel_Availability_Template.xlsx")

goXLSX.SaveWorkbookAs(lnWb, "C:\Users\RobW\Downloads\Excel_Availability.xlsx")


[Excel_Availability_Template.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/14289845/Excel_Availability_Template.xlsx)

[Excel_Availability.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/14289847/Excel_Availability.xlsx)

**Comment by ggreen86** [comment]
Rob—

I checked the file “Excel_Availability_Template.xlsx” random cell properties and the cells that I checked were set to Locked=True.  I checked cells in the prefilled text areas and in cells that have no text entered.  All checked had the Locked=True set.  When checking the file after being opened and then re-saved to a new file name, the cells still had the setting Locked=True.  See below screen-shot.

***@***.***

Can you provide the specific cells that do not have this setting set?  Right now I cannot duplicate or find any problem in the protection setting.

Greg

**Comment by rawilliamsjr** [comment]
Greg,

Sorry for wasting your time. I thought I had specified the cells. The cells not locked are the Qty., Retail, and SKU column header labels.



Robert Williams

Phone 971.217.0850

www.advancedgrowersolutions.com<http://www.advancedgrower.com/>

***@***.******@***.***>
[cid:b8f6251a-221f-45f7-a858-bde7054bc176]

________________________________

**Comment by ggreen86** [comment]
Rob--

I believe I now have the class reading the sheet protection settings correctly and then writing back to the new workbook.  Please try the attached R41 Beta 4 and let me know how it works.  

I still have to work on the retaining/setting of the password.

Thank you.

Greg

[WorkbookXLSX R41 Beta 4.zip](https://github.com/ggreen86/XLSX-Workbook-Class/files/14319399/WorkbookXLSX.R41.Beta.4.zip)

**Comment by rawilliamsjr** [comment]
All other issues are now working. I know you are still working on the password and the sheet protection. Just wanted to pass this along. I received an error message when I opened a workbook that had sheet protection enabled after saving it under a different name.

[cid:3f46b49f-c79e-42a4-9624-abdf03b3b61e]



Robert Williams

Phone 971.217.0850

www.advancedgrowersolutions.com<http://www.advancedgrower.com/>

***@***.******@***.***>
[cid:07665086-c69b-456b-abd1-4f934f9ca2f7]

________________________________

**Comment by ggreen86** [comment]
Closing issue; corrected in R41
