### ISSUE TITLE
Ease of use in creating a workbook , renaming and retyping columns

### ISSUE THREAD

**Issue by bzaner** [ggreen86/XLSX-Workbook-Class#11]
i have used oExcel.SaveTableToWorkBook("BuildTrend", filenam,.t.,.t.)  to create the xlsx file but, i want a couple of the field (column) names to be longer and have spaces in them.  i also want all the numeric fields (columns) to be currency.

would you modify the output xlsx  or go the route of creating the file from scratch and dumping the data into it?  Which is easier for a novice to this class?
if it is to modify the output,  i dont know how to get the sheet name with lnsh1 = oExcel.GetSheetName(lnwb,1).  What is the sheet id parameter?

The real problem i have is that there are no examples for the novice in the documentation for the class s of there is a clear line of thought for a process.

**Comment by bzaner** [comment]
is anyone there to pay attention to this issue.  if so, is there any documentation on examples of the use of the class.

**Comment by ggreen86** [comment]
I suggest looking at the Demo() method.  It shows a lot of examples of using the class.  In your case, I would use not use the direct write methods but write to each cell the value and format.


________________________________

**Comment by bzaner** [comment]
Thanks for the response.

 

I have looked at the demo method and it only shows how to create a workbook from scratch and put data into it.  

 

I had thought that, since there are methods that talk about reading a workbook, it might be easy just to create it with the simple SaveTableToWorkBook and then just modify the header line  on a couple of columns and the type of field on a couple columns.  The demo method does not assist me in finding out how the access the sheet and does not include any of the other tools for going in that direction.

 

Since I cannot seem to make that work,  I will have to go the other direction.

 

Thanks,

 

Byron

_______________________________

Construction Software…

                        …turning your time into profit

                        <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2fconstruction&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=scXnVFBi50VZYyzC1g3LiKulMaVw3p5vmbxn4Rqmm0U%3d> 

                <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2f&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=6i8O%2fQOtASc7PymxlBtz9X90SPMWnZ6Jn7OynrvCmsc%3d> http://www.priosoft.com

      888-394-0252  /  410-627-8891

                 <https://www.facebook.com/priosoft/>    <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.linkedin.com%2fcompany%2f1545521%3ftrk%3dtyah&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=d8N7U2LHl2tvFcxzVSJxPh9r4YM%2fxHU%2fEVv719fq07o%3d>   <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2ftwitter.com%2fpriosoft&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=RLbGW3sfRJcBF25ZpTn5ue6MbG6xTWtmDTbUjXFOWhU%3d>  <https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fplus.google.com%2f105070244357160453152%2fposts&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=33ZP%2b5GfXP1oQbxDxP3AYglacR4Kff1MvImO8aM%2fqcQ%3d>   <https://www.youtube.com/c/priosoft>

**Comment by bzaner** [comment]
the commands i put together were
oExcel = NEWOBJECT("VFPXWorkbookXLSX","VFPXWorkbookXLSX")
oExcel.SaveTableToWorkBook("BuildTrend", filenam,.t.,.t.)   &worked fine
lnWb = oExcel.OpenXlsxWorkbook(filenam)	&gave lnWB = 0
loSheets = goExcel.GetWorkbookSheets(lnWb)	&gave loSheets = 0
 lnsh1 = oExcel.GetSheetName(lnwb,1)  & gave an error

**Comment by ggreen86** [comment]
Because you want custom cell formatting, the direct write workbook functions will not do what you want.  They only use default formatting or formatting of a grid; the methods do not use the data type.  So you will need to create a workbook, add the sheet and then iterate over your table and write the field values to the cells.  Then create a cell formatting style and apply to the cells based on your formatting requirements.  Then you save the workbook.  This is a slower process but it will accomplish what you want.

**Comment by bzaner** [comment]
It would be helpful if, in the demo() or somewhere else in the documentation, you would specify what you just said so other people don’t caught in this thought process.  I appreciate you answer.

 

What situations are the getworksheet method and those methods designed to handle?

 

Thanks,

 

Byron

_______________________________

Construction Software…

                        …turning your time into profit

                        <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2fconstruction&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=scXnVFBi50VZYyzC1g3LiKulMaVw3p5vmbxn4Rqmm0U%3d> 

                <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2f&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=6i8O%2fQOtASc7PymxlBtz9X90SPMWnZ6Jn7OynrvCmsc%3d> http://www.priosoft.com

      888-394-0252  /  410-627-8891

                 <https://www.facebook.com/priosoft/>    <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.linkedin.com%2fcompany%2f1545521%3ftrk%3dtyah&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=d8N7U2LHl2tvFcxzVSJxPh9r4YM%2fxHU%2fEVv719fq07o%3d>   <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2ftwitter.com%2fpriosoft&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=RLbGW3sfRJcBF25ZpTn5ue6MbG6xTWtmDTbUjXFOWhU%3d>  <https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fplus.google.com%2f105070244357160453152%2fposts&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=33ZP%2b5GfXP1oQbxDxP3AYglacR4Kff1MvImO8aM%2fqcQ%3d>   <https://www.youtube.com/c/priosoft>

**Comment by bzaner** [comment]
A suggestion for the future of the people doing any work on this class would be a means of doing the renaming of columns and changes to the column type after doing the simple direct convert method.  Life for the user would be easier.

 

Thanks,

 

Byron

_______________________________

Construction Software…

                        …turning your time into profit

                        <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2fconstruction&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=scXnVFBi50VZYyzC1g3LiKulMaVw3p5vmbxn4Rqmm0U%3d> 

                <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2f&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=6i8O%2fQOtASc7PymxlBtz9X90SPMWnZ6Jn7OynrvCmsc%3d> http://www.priosoft.com

      888-394-0252  /  410-627-8891

                 <https://www.facebook.com/priosoft/>    <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.linkedin.com%2fcompany%2f1545521%3ftrk%3dtyah&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=d8N7U2LHl2tvFcxzVSJxPh9r4YM%2fxHU%2fEVv719fq07o%3d>   <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2ftwitter.com%2fpriosoft&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=RLbGW3sfRJcBF25ZpTn5ue6MbG6xTWtmDTbUjXFOWhU%3d>  <https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fplus.google.com%2f105070244357160453152%2fposts&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=33ZP%2b5GfXP1oQbxDxP3AYglacR4Kff1MvImO8aM%2fqcQ%3d>   <https://www.youtube.com/c/priosoft>

**Comment by ggreen86** [comment]
That is not as easy as you might think in terms of a generic change of column data types.  The intent of the class is to provide a means for developers to write XLSX spreadsheets without automation and not a complete anything can be done with the class including the "kitchen-sink" via a single method call.  The class provides the capability that you want; but you have to write the code to call the appropriate methods in the necessary sequence.  That is the job of the developer.


________________________________

**Comment by bzaner** [comment]
Do you know where I might find standard #Defines for things like the ones in red? I have searched the internet and cannot find them.  They are used in VFPxWorkbookXlsx and not defined anywhere.  The following are statements form VFPxWorkbookXlsx.

 

this.SetCellBorder(lnWb, lnSh, 2, 1, BORDER_TOP+BORDER_BOTTOM, BORDER_STYLE_THICK,  RGB(100,150,200))

this.SetCellBorder(lnWb, lnSh, 5, 1, BORDER_LEFT+BORDER_RIGHT, BORDER_STYLE_DOUBLE, RGB(255,0,0))

 

 

 

Thanks,

 

Byron

_______________________________

Construction Software…

                        …turning your time into profit

                        <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2fconstruction&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=scXnVFBi50VZYyzC1g3LiKulMaVw3p5vmbxn4Rqmm0U%3d> 

                <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2f&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=6i8O%2fQOtASc7PymxlBtz9X90SPMWnZ6Jn7OynrvCmsc%3d> http://www.priosoft.com

      888-394-0252  /  410-627-8891

                 <https://www.facebook.com/priosoft/>    <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.linkedin.com%2fcompany%2f1545521%3ftrk%3dtyah&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=d8N7U2LHl2tvFcxzVSJxPh9r4YM%2fxHU%2fEVv719fq07o%3d>   <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2ftwitter.com%2fpriosoft&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=RLbGW3sfRJcBF25ZpTn5ue6MbG6xTWtmDTbUjXFOWhU%3d>  <https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fplus.google.com%2f105070244357160453152%2fposts&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=33ZP%2b5GfXP1oQbxDxP3AYglacR4Kff1MvImO8aM%2fqcQ%3d>   <https://www.youtube.com/c/priosoft>

**Comment by bzaner** [comment]
all the numeric defines are defined in the documentation

**Comment by bzaner** [comment]
I cannot figure out how to make the fields pointed to currency fields.



 

      USE (TRIM(control.snetpath)+'copy'+tmpfl) ALIAS buildtrend

      GO top

      xrows = RECCOUNT()

      filenam= PUTFILE('Save as file', 'Job-'+ALLTRIM(IIF(actual,budgest.jobno,evlist2.jobno))+'.xlsx' ,'xls')

      tcExcelWhereExpr = ' '

*     DO CopyToExcel IN appendxlsx WITH filenam, "Sheet1", "copyer"

      IF file(JUSTFNAME(filenam))

            DELETE FILE(filenam)

      endif

      LOCAL oExcel

      #DEFINE False .f.

      #DEFINE True .t.

      #DEFINE CELL_FORMAT_CURRENCY_PAREN $#,##0.00;($#,##0.00)

      oExcel= NEWOBJECT("VFPXWorkbookXLSX","VFPXWorkbookXLSX")

 

      LOCAL lnWb, lnSh1, lnRow, lnCol, lnSh2, lnSh3, lnSh4, lnCnt, lnFormat, llBoolean, lcNamedRange

      LOCAL lnSh6, lnSh5, loInline, lnStyle1, lnStyle2, lnBorders, lcString

      lnWb = oExcel.CreateWorkbook(filenam)

      IF lnWb = 0

            RETURN .f.

      ENDIF

 

      lnSh1 = oExcel.AddSheet(lnWb, "Sheet 1")

      IF lnSh1 = 0

            RETURN False

      ENDIF

      oExcel.FreezePanes(lnWb, lnSh1, 1, 2)

 

      llBoolean = True

      FOR lnRow=1 TO xrows 

            FOR lnCol=1 TO 5

                  oExcel.SetCellValue(lnWb, lnSh1, lnRow, lnCol, SYS(2015))

            ENDFOR

            llBoolean = !llBoolean

            oExcel.SetCellValue(lnWb, lnSh1, lnRow, 10, llBoolean)

      ENDFOR

      oExcel.SetRowHeight(lnWb, lnSh1, 6, 25)

      lnStyle2  = oExcel.CreateFormatStyle(lnWB)   && Create the base style definition

      oExcel.AddStyleFont(lnWB, lnStyle2, "Arial", 10, False, False)

*     oExcel.SetCellStyleRange(lnWB, lnSh1, 4, 1, 4, 9, lnStyle2)

      oExcel.SetColumnWidth(lnWb, lnSh1, 1, 55)

      oExcel.SetColumnWidth(lnWb, lnSh1, 2, 75)

      oExcel.SetColumnWidth(lnWb, lnSh1, 3, 15)

      oExcel.SetColumnWidth(lnWb, lnSh1, 4, 15)

      oExcel.SetColumnWidth(lnWb, lnSh1, 5, 15)

      lnRow = 1

      oExcel.SetCellValue(lnWb,lnSh1,lnRow,1, 'Account Code')

      oExcel.SetCellValue(lnWb,lnSh1,lnRow,2, 'Description')

      oExcel.SetCellValue(lnWb,lnSh1,lnRow,3, 'Quantity')

      oExcel.SetCellValue(lnWb,lnSh1,lnRow,4, 'Unit Price')

      oExcel.SetCellValue(lnWb,lnSh1,lnRow,5, 'Amount')

      FOR lnRow=2 TO xrows 

*           oExcel.SetCellValue(lnWb, lnSh3, lnRow, 4, -13355.20)

            oExcel.SetCellNumberFormat(lnWb, lnSh1, lnRow, 4, "$#,##0.00;($#,##0.00")

*           oExcel.SetCellValue(lnWb, lnSh3, lnRow, 5, -13355.20)

            oExcel.SetCellNumberFormat(lnWb, lnSh1, lnRow, 5, "$#,##0.00;($#,##0.00")

      ENDFOR

      SELECT buildtrend

      GO TOP

      skip

      SCAN WHILE RECNO() > 1 .and. RECNO()<= RECCOUNT()

            lnRow= RECNO()

            oExcel.SetCellValue(lnWb,lnSh1,lnRow,1, buildtrend.account)

            oExcel.SetCellValue(lnWb,lnSh1,lnRow,2, buildtrend.DESCRIPT)

            oExcel.SetCellValue(lnWb,lnSh1,lnRow,3, buildtrend.Quantity)

            oExcel.SetCellValue(lnWb,lnSh1,lnRow,4, buildtrend.Unit_Price)

            oExcel.SetCellValue(lnWb,lnSh1,lnRow,5, buildtrend.Amount)

      endscan

      

 

      oExcel.SaveWorkbook(lnWb)

      RELEASE cfilexl, cfiletxl,lnWb, lnSh1, lnRow, lnCol

 

 

Thanks,

 

Byron

_______________________________

Construction Software…

                        …turning your time into profit

                        <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2fconstruction&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=scXnVFBi50VZYyzC1g3LiKulMaVw3p5vmbxn4Rqmm0U%3d> 

                <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2f&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=6i8O%2fQOtASc7PymxlBtz9X90SPMWnZ6Jn7OynrvCmsc%3d> http://www.priosoft.com

      888-394-0252  /  410-627-8891

                 <https://www.facebook.com/priosoft/>    <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.linkedin.com%2fcompany%2f1545521%3ftrk%3dtyah&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=d8N7U2LHl2tvFcxzVSJxPh9r4YM%2fxHU%2fEVv719fq07o%3d>   <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2ftwitter.com%2fpriosoft&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=RLbGW3sfRJcBF25ZpTn5ue6MbG6xTWtmDTbUjXFOWhU%3d>  <https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fplus.google.com%2f105070244357160453152%2fposts&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=33ZP%2b5GfXP1oQbxDxP3AYglacR4Kff1MvImO8aM%2fqcQ%3d>   <https://www.youtube.com/c/priosoft>

**Comment by bzaner** [comment]
i have added AddStyleNumericFormat and changed the iteration of the numeric cells an nothing changes.

oExcel.AddStyleFont(lnWB, lnStyle2, "Arial", 10, False, False)
oExcel.AddStyleNumericFormat(lnWB,CELL_FORMAT_CURRENCY_PAREN)
oExcel.SetColumnWidth(lnWb, lnSh1, 1, 55)
oExcel.SetColumnWidth(lnWb, lnSh1, 2, 75)
oExcel.SetColumnWidth(lnWb, lnSh1, 3, 15)
oExcel.SetColumnWidth(lnWb, lnSh1, 4, 15)
oExcel.SetColumnWidth(lnWb, lnSh1, 5, 15)
lnRow = 1
oExcel.SetCellValue(lnWb,lnSh1,lnRow,1, 'Account Code')
oExcel.SetCellValue(lnWb,lnSh1,lnRow,2, 'Description')
oExcel.SetCellValue(lnWb,lnSh1,lnRow,3, 'Quantity')
oExcel.SetCellValue(lnWb,lnSh1,lnRow,4, 'Unit Price')
oExcel.SetCellValue(lnWb,lnSh1,lnRow,5, 'Amount')
SELECT copyer
GO TOP
skip
SCAN WHILE RECNO() > 1 .and. RECNO()<= RECCOUNT()
	lnRow= RECNO()
	oExcel.SetCellValue(lnWb,lnSh1,lnRow,1, copyer.account)
	oExcel.SetCellValue(lnWb,lnSh1,lnRow,2, copyer.DESCRIPT)
	oExcel.SetCellValue(lnWb,lnSh1,lnRow,3, copyer.Quantity)
	oExcel.SetCellValue(lnWb,lnSh1,lnRow,4, copyer.Unit_Price)
	oExcel.SetCellNumberFormat(lnWb, lnSh1, lnRow, 4, CELL_FORMAT_CURRENCY_PAREN)
	oExcel.SetCellValue(lnWb,lnSh1,lnRow,5, copyer.Amount)
	oExcel.SetCellNumberFormat(lnWb, lnSh1, lnRow, 5, CELL_FORMAT_CURRENCY_PAREN)
endscan

**Comment by ggreen86** [comment]
All the DEFINE statements are included in the ZIP file -- see the .h file


________________________________

**Comment by bzaner** [comment]
This is a catch in createexcellfile right at the end as it is creating the file.  The message includes the filter that gets these items on the screen.  I take that table and, from it, create the table “copyer” which contains some of the data.  It is from the “copyer” file that I create the workbook so this table and its filter are not directly associated with the workbook. 

 

The code I created for creating the workbook is the last message to you.

It creates the correct workbook on my computer but not on the customer’s computer so, I put messagebox’s all through the code to narrow down why.  It comes down to this and it is the code right at the end of  createexcelfile. 

I put the values with each.  I inserted the code that is in red to get the exact error.

 

      TRY

            FOR EACH loFile IN loFolder

      MESSAGEBOX( 'lofolder'+STR(loFolder.count))  = 4

                  lnCountBefore = loShell.NameSpace(tcTempPath).Items.Count

      MESSAGEBOX( 'lnCountBefore  '+STR(lnCountBefore)) = 4

                  loShell.NameSpace(lcZipFile).MoveHere(loFile, FOF_SILENT)

                  lczipfile = c:\programfiles (x86)\priosoft\Job-273.zip

-------------------------loFile is the problem--------------------

                  DO WHILE lnCountBefore = loShell.NameSpace(tcTempPath).Items.Count

                        apiSleep(50)

                  ENDDO

            ENDFOR

 

      CATCH TO loException

            pos = AT('RequestProcessor',loException.message)+18

            messagebox('Error: '+TRIM(loException.LineContents)+ SUBSTR(loException.message,pos))

            this.ErrorLevelId = 12

            RAISEEVENT(this, "OnShowErrorMessage", 12, "CreateExcelFile - Failed to add contents to Zip file"+ CR + loException.Message)

            SET STEP ON

            ERASE (lcZipFile)

            DO CASE

            CASE loException.ErrorNo = 1943

            OTHERWISE

                  SET STEP ON

            ENDCASE

      ENDTRY

      TRY

            apiMoveFile(lcZipFile, FORCEEXT(lcZipFile, "xlsx"))

 

      CATCH TO loException

            pos = AT('RequestProcessor',loException.message)+18

            errtxt = SUBSTR(loException.message,pos)

            messagebox('Error: '+TRIM(loException.LineContents)+errtxt)

return

            this.ErrorLevelId = 13

            RAISEEVENT(this, "OnShowErrorMessage", 13, "CreateExcelFile - Rename failed"+ CR + loException.Message)

            SET STEP ON

      ENDTRY

ENDIF

 

 

 

 

Thanks,

 

Byron

_______________________________

Construction Software…

                        …turning your time into profit

                        <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2fconstruction&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=scXnVFBi50VZYyzC1g3LiKulMaVw3p5vmbxn4Rqmm0U%3d> 

                <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.priosoft.com%2f&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=6i8O%2fQOtASc7PymxlBtz9X90SPMWnZ6Jn7OynrvCmsc%3d> http://www.priosoft.com

      888-394-0252  /  410-627-8891

                 <https://www.facebook.com/priosoft/>    <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.linkedin.com%2fcompany%2f1545521%3ftrk%3dtyah&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=d8N7U2LHl2tvFcxzVSJxPh9r4YM%2fxHU%2fEVv719fq07o%3d>   <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2ftwitter.com%2fpriosoft&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=RLbGW3sfRJcBF25ZpTn5ue6MbG6xTWtmDTbUjXFOWhU%3d>  <https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fplus.google.com%2f105070244357160453152%2fposts&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=33ZP%2b5GfXP1oQbxDxP3AYglacR4Kff1MvImO8aM%2fqcQ%3d>   <https://www.youtube.com/c/priosoft>

**Comment by jlindgren0512** [comment]
This works great on my computer when I run it in my application.  When I create an exe and move it to another network, it says it creates the xlsx file but it never does.  Anyone have any insight?

LOCAL lcTable, lcExcel
lcExcel = "S:\Customer Database Reports\Export\Orders_"+ SUBSTR(TTOC(ldstartdate,1),1,8) + "_" + SUBSTR(TTOC(ldenddate,1),1,8) + ".xlsx"
lcTable = ADDBS(SYS(2004)) + "tblOrders.dbf"
lcTable = LOCFILE(lcTable)

IF !ISNULL(lcTable) .AND. FILE(lcTable)
	thisform.clsVFPxWorkbookXLSX.SaveTabletoWorkbook(lcTable, lcExcel, .T., .T.)
	WAIT WINDOW "Saved To "+lcExcel NOWAIT
ENDIF

**Comment by ggreen86** [comment]
What happens if you save to the local drive instead of a mapped drive with the same computer?

Greg

________________________________
