### ISSUE TITLE
Missing variables in VFPxWorkbookXLSX.h

### ISSUE THREAD

**Issue by rdewild** [ggreen86/XLSX-Workbook-Class#117]
Hello Greg.
I am currently using: WorkbookXLSX R40

When making a call to loExcel.SaveTableToWorkbookEx() I have confirmed all temporary files are created.
However, during the call to this.CreateExcelFile and then this.addfilestozip() I get the following error:
CreateExcelFile - Failed to add contents to Zip file
Variable 'FOF_NOCONFIRMATION' is not found.

I found that although  FOF_SILENT is defined in VFPxWorkbookXLSX.h
The following two are not.
FOF_NOCONFIRMATION
FOF_NOERRORUI

I believe I found the proper values for this variables here: https://learn.microsoft.com/en-us/windows/win32/shell/folder-movehere
But thought I'd let you know so that you can include them.

This solved my error and the XLSX is now correctly written.
Thank you for a great class.

**Comment by ggreen86** [comment]
Hello--

Thank  you for this message; however, these two are in the include file:

![image](https://github.com/ggreen86/XLSX-Workbook-Class/assets/28057069/ccc2e494-a00e-4d79-ac24-ca3db5084f74)

Greg
