### ISSUE TITLE
GetNodeAttributeBoolean caused a "column does not accept null values" error

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#121]
I ran into this a while ago so I forget the circumstances, but this fixed it:

```
IF EMPTY(lcAttrValue)
*** DH 2024-05-26: return .F. not NULL to prevent "column does not accept null values" errors
*	llAttrValue = .NULL.
	llAttrValue = .F.
```

**Comment by ggreen86** [comment]
Thank you -- I have added this to R46.  I believe you added this fix to the hidden method GetNodeAttributeBoolean.

**Comment by DougHennig** [comment]
I don't see that change in the R46 you sent me 10/01/2024. Is it in a later build?

**Comment by ggreen86** [comment]
Yes, it is in a later build.
