### ISSUE TITLE
SaveGridToWorkbook automatically create formula from cell value

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#126]
I added some new functionality to SaveGridToWorkbook if you're interested. If the value of a cell in a grid starts with '=', treat it like a formula. Here's the code:

```
*-*		Add the cell data values and cell formatting
		SELECT &lcGridAlias
		SCAN
			lnRow = lnRow + 1
			RAISEEVENT(this, "OnShowStatusMessage", 3, lnRow)
			FOR lnCol=1 TO lnColCount
				loColumn = toGrid.Columns(laColOrder[lnCol, 2])
				lcField  = loColumn.ControlSource
				lxCellValue = EVALUATE(lcField)
				IF loGrid.Columns(laColOrder[lnCol, 2]).FieldPercent
					lxCellValue = lxCellValue / 100
				ENDIF
*** DH 2024-02-23: treat a value starting with "=" as a formula
*				this.SetCellValue(lnWB, lnSh, lnRow, lnCol+tnBegCol-1, lxCellValue)
				if vartype(lxCellValue) = 'C' and left(lxCellValue, 1) = '='
					This.SetCellFormula(lnWB, lnSh, lnRow, lnCol+tnBegCol-1, strtran(lxCellValue, '{ROW}', transform(lnRow), -1, -1, 1))
				else
					this.SetCellValue(lnWB, lnSh, lnRow, lnCol+tnBegCol-1, lxCellValue)
				endif vartype(lxCellValue) = 'C' ...
*** DH 2024-02-23: end of change
				IF loGrid.Columns(laColOrder[lnCol, 2]).DynamicProperties
```

**Comment by ggreen86** [comment]
I will add this feature into the next release.  

I am also considering how I might add formula support to SaveGridToWorkbook and SaveGridToWorkbookEx methods by adding a custom property to the grid column object.  I use a custom class for the columns which is then assigned to the grid (also a custom class) via the MemberClass property.  So, it is easy for me to define the property.  It could also be added at run-time if not using a custom column class.  I am thinking to name the property 'ColumnFormula' and the developer would put the desired formula; i.e., SUM, AVG, etc., to be added after the last row is outputted as the property value.  What are your thoughts on this approach?

Greg

**Comment by DougHennig** [comment]
Sounds like a good idea.

**Comment by ggreen86** [comment]
Specifying formulas for grids has now been implemented in R45.  Both the inline method (proposed by Doug Hennig) of using a '=' sign as the first character (also checks for parenthesis) for denoting a formula and also using custom column properties on the grid is available.  See the Release Notes and the User Documentation for more information.

**Comment by DougHennig** [comment]
One suggestion: trim the value before checking the right character:

```
*// DH 05/22/2025: TRIM lxCellValue in case there are trailing spaces
*				IF VARTYPE(lxCellValue) = "C" .AND. LEFT(lxCellValue, 1) = "=" .AND. ATC("(", lxCellValue) > 0 .AND. RIGHT(lxCellValue, 1) = ")"   && Suggestion for assigning formulas by Doug Hennig
				IF VARTYPE(lxCellValue) = "C" .AND. LEFT(lxCellValue, 1) = "=" .AND. ATC("(", lxCellValue) > 0 .AND. RIGHT(trim(lxCellValue), 1) = ")"   && Suggestion for assigning formulas by Doug Hennig
```
