### ISSUE TITLE
OpenXlsxWorkbookEx: empty string when the cell contains "<"

### ISSUE THREAD

**Issue by foxproc** [ggreen86/XLSX-Workbook-Class#127]
Hello!

Thank you for your great program!

When OpenXlsxWorkbookEx fills the cursor xl_tmpstrings it already makes the translation from xml to normal text, thus substituting, for instance, "&lt;" by "<". When it wants to fill xl_sheetcells, it calls again GetStringXML but since the text already contains "<", the code
```
this.oXDOM.loadXML("<value>" + tcString + "</value>")
this.oXDOM.Text
```
returns an empty string.

**Comment by foxproc** [comment]
Hello! Thank for your answer.

I'm attaching the file where I saw the problem. I'm using version R44 of your class.

The rows 17 and 63, that contain the character "<" were empty in the cursor.

Doing the debug, line by line, I'd say the problem is created by the object oXDOM.

When you call

this.oXDOM.loadXML("<value>" + tcString + "</value>")

the value of tcString is "Ass Inv_Perni_Piastr_ABB <=50A_LB".

In the next line when you call

lcString = this.oXDOM.Text

lcString it's empty.

I solved substituting
lcCellValue = this.GetStringXML(ALLTRIM(xl_tmpstrings.stringval))
by
lcCellValue = ALLTRIM(xl_tmpstrings.stringval)
but I don't know if that broke other uses of the library.

Mario Lucioni

________________________________

**Comment by ggreen86** [comment]
Can you provide a workbook file (xlsx) that contains the above issue of a cell containing the character '<' in the string?  Basically, this should not happen as the '<' character should be converted by whatever created the original workbook to be represented as '&lt;'.  The inclusion of the character '<' would cause any xml parser to reject the xml as badly formed.

**Comment by foxproc** [comment]
Hello: In my email I had sent you the file that gave me the problem, but probably it was not forwarded by github to you. How can I send it to you?

My program does simply this:

```
w_EXCEL=NEWOBJECT("VFPxWorkbookXLSX", "VFPxWorkbookXLSX.vcx", "", 1250)
w_EXCEL.OpenXlsxWorkbookex(w_PATH,1)
```

w_PATH is the name of the excel file. I want to obtain the cursor **xl_sheetcells**.

The problem, I think, is you do the conversion from XML to text twice. 

First, in the **OpenXslxWorkbookEx**, when you fill the xl_tmpstrings cursor by reading the "\xl\sharedstrings.xml":

`INSERT INTO xl_tmpstrings (id, stringval) VALUES (lnNode, this.**GetStringXML**(lcXMLText))`

Then the second time in the method **ProcessSheet**, in the case option
CASE lcType == "s"                               && Cell contains string index; get value from xl_tmpstrings
when you call
lcCellValue = this.GetStringXML(ALLTRIM(xl_tmpstrings.stringval))

which is not necessary because the values in the field xl_tmpstrings.stringval have already been converted.

**Comment by foxproc** [comment]
Thank you very much! I confirm that the problem's been solved.

**Comment by ggreen86** [comment]
This is now corrected in R45.
