### ISSUE TITLE
Error in dcterms:created

### ISSUE THREAD

**Issue by martinsbalcuns** [ggreen86/XLSX-Workbook-Class#129]
There are problems opening with Excel if the time is entered in the following form:
<dcterms:created xsi:type="dcterms:W3CDTF">2024-10-27T19:15:30+-2:00</dcterms:created>
Fix if: <dcterms:created xsi:type="dcterms:W3CDTF">2024-10-28T07:05:48Z</dcterms:created>
It would be good if method: writesupportxmls had the same as method: writedirectxml, i.e. ' + TTOC(DATETIME(), 3) + 'Z

**Comment by ggreen86** [comment]
This code has been reverted back to how it was being written with the z-notation in R45.  See the Release Notes for more information.
