### ISSUE TITLE
Date not being stored in Excel - R45Beta2

### ISSUE THREAD

**Issue by Ajitweb** [ggreen86/XLSX-Workbook-Class#131]
Hello Greg,

```
loExcel = NEWOBJECT("VFPxWorkbookXLSX", "..\vfpxworkbookxlsx.vcx")
lnWb = loExcel.CreateWorkbook("C:\Temp\R45BETA2.xlsx")

IF lnWb > 0
 lnSh = loExcel.AddSheet(lnWb, "Test")
 loExcel.SetCellValue(lnWb, lnSh, 1, 1, "I am R45BETA2")
 loExcel.SetCellValue(lnWb, lnSh, 2, 1, DATE())
 loExcel.SetCellValue(lnWb, lnSh, 3, 1, DMY(DATE()))
 loExcel.SaveWorkbook(lnWb)
ENDIF
```

I don't see the date in the second row
Can u check from your side

Ajit

**Comment by ggreen86** [comment]
I have confirmed the error.  I will try to fix today or tonight.

From: Ajit Abraham ***@***.***>
Sent: Tuesday, November 12, 2024 7:40 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Date not being stored in Excel - R45Beta2 (Issue #131)


Hello Greg,

loExcel = NEWOBJECT("VFPxWorkbookXLSX", "..\vfpxworkbookxlsx.vcx")

lnWb = loExcel.CreateWorkbook("C:\Temp\R45BETA2.xlsx")



IF lnWb > 0

 lnSh = loExcel.AddSheet(lnWb, "Test")

 loExcel.SetCellValue(lnWb, lnSh, 1, 1, "I am R45BETA2")

 loExcel.SetCellValue(lnWb, lnSh, 2, 1, DATE())

 loExcel.SetCellValue(lnWb, lnSh, 3, 1, DMY(DATE()))

 loExcel.SaveWorkbook(lnWb)

ENDIF

I don't see the date in the second row
Can u check from your side

Ajit

**Comment by ggreen86** [comment]
Ajit--

Thank you for identifying this bug.  Had to do with changes that were added to support the standard cell formatting.  I believe it is now fixed.  I have uploaded it has R45 beta 3 (see the downloads).

Greg
