### ISSUE TITLE
SaveGridToWorkbookEx creates incomplete file

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#18]
The Excel zip file created by SaveGridToWorkbookEx doesn't contain sharedStrings.xml so later opening it with OpenXLSXWorkbook fails. I didn't try it but I suspect SaveTableToWorkbookEx has the same issue.

**Comment by ggreen86** [comment]
Doug--


Yes, you are right about the sharedStrings.xml causing the problem and both methods would be the same.  I have removed the requirement for the sharedStrings.xml and now test for it and open it if it is present.  I have tested the fix and is working now.  I will be posting an update after I have fixed the other issue you found.


Greg

________________________________
