### ISSUE TITLE
Appending new sheet to existing documents creates damaged file

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#19]
I created an Excel document using SaveGridToWorkbook, then later appended to it using code like this:

lnWB = loExcel.OpenXLSXWorkbook(lcOutputFileName)
lcSheet = 'My New Sheet'
loReturn = loExcel.SaveGridToWorkbook(loGrid, lnWB, .T, .T., lcSheet)

When I open the document in Excel, I get a warning that there's unreadable content. If I tell Excel to repair it, it opens it just fine and displays this:

Repaired Records: Format from /xl/styles.xml part (Styles)
Repaired Records: Cell information from /xl/worksheets/sheet2.xml part

I've attached the created document if that helps.
[ExcelTest.xlsx](https://github.com/ggreen86/XLXS-Workbook-Class/files/2115902/ExcelTest.xlsx)

**Comment by ggreen86** [comment]
Doug--


I have found the cause of the warning and now looking at how to fix the issue.  It has to do with the number of cell formatting styles defined in the styles.xml and how they are referenced.  The referenced style count for a cell formatting is getting set outside of the actual count and this is the warning given by Excel.  Hopefully will have a fix soon.

Greg

________________________________
