### ISSUE TITLE
CreateExcelFile does not always work properly

### ISSUE THREAD

**Issue by CHamlinPNP** [ggreen86/XLSX-Workbook-Class#22]
This is on a Windows 10 Pro x64. For small/simple spreadsheets I do not appear to have any issues. For larger workbooks with multiple sheets...it does not always complete properly so sometimes it leaves it with .ZIP extension...other times not all of the files have been added properly...etc. Just seems to have many issues with this routine.

**Comment by ggreen86** [comment]
I have not experienced any problems.  I have worked with workbooks that are over 10M in size and have over 10 sheets.  Can you provide any sample data that reproduces the problem?

**Comment by CHamlinPNP** [comment]
I really have lost track of this...I reported it a year and a half ago and a lot has changed since then. I know I have modified the .ZIP part of it with some other libraries which corrected for this.

**Comment by ggreen86** [comment]
Sorry for the VERY LATE REPLY above.  There was a number of releases during this period; perhaps one of those corrected your problem.  I am closing this issue.
