### ISSUE TITLE
Support column InputMask and Format

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#27]
Have SaveGridToWorkbook and SaveGridToWorkbookEx support the InputMask and Format properties of each grid column, at least for numeric values. For example, with Format = "$" and InputMask = "999,999.99", use the appropriate format in Excel.

**Comment by ggreen86** [comment]
Doug--

Sorry for the late reply -- yes I believe it could be done without too much of a performance hit.  Not sure when I can do this but will keep this as a to-do item.  Right now I am busy building a house for my wife and I (I am actually doing much of the work myself) -- it is nearing a point that we can move in.

Greg

________________________________

**Comment by DougHennig** [comment]
Hi Greg.

I added support for % formats to SaveGridToWorkbookEx with the following changes:

*** DH 2020-03-17: handle all numeric types
***			CASE lcVarType = "N"
			CASE lcVarType $ "NFIBY"
				DO CASE
*** DH 2020-03-17: handle % format
					CASE '%' $ loGrid.Columns[lnCol].InputMask and '.' $ loGrid.Columns[lnCol].InputMask
						loGrid.Columns[lnCol].NumFmtsIndex = CELL_FORMAT_PERCENT_FLOAT

					CASE '%' $ loGrid.Columns[lnCol].InputMask
						loGrid.Columns[lnCol].NumFmtsIndex = CELL_FORMAT_PERCENT_INTEGER
*** DH 2020-03-17: end of new code
					CASE EMPTY(loGrid.Columns[lnCol].Format)
						loGrid.Columns[lnCol].NumFmtsIndex = 0

					CASE loGrid.Columns[lnCol].Format = "L"
						loGrid.Columns[lnCol].NumFmtsIndex = 99

					CASE loGrid.Columns[lnCol].Format = "R"
						lnNumFmtsId = lnNumFmtsId + 1
						loGrid.Columns[lnCol].NumFmtsIndex = lnNumFmtsId + 164
						loGrid.Columns[lnCol].FormatCode   = ''

					CASE loGrid.Columns[lnCol].Format = "$"
						loGrid.Columns[lnCol].NumFmtsIndex = CELL_FORMAT_CURRENCY_RED_PAREN
				ENDCASE

			CASE lcVarType = "T"
				loGrid.Columns[lnCol].NumFmtsIndex = CELL_FORMAT_DATETIME_DDMMMYYYY_TTAM

*** DH 2020-03-17: commented this out since handled above
*			CASE lcVarType = "Y"
*				loGrid.Columns[lnCol].NumFmtsIndex = CELL_FORMAT_CURRENCY_RED_PAREN
		ENDCASE

**Comment by ggreen86** [comment]
Code changes incorporated into Release 32.
