### ISSUE TITLE
Question about creating a link as a cell value

### ISSUE THREAD

**Issue by nmossvfp** [ggreen86/XLSX-Workbook-Class#28]
I recently came across this class and really appreciate it - Thanks!

Something I don't see in the demo and haven't been able to figure out is how do I create a cell which is a clickable link to display data on another sheet?

So for example if I have a workbook with 4 sheets captioned 'Summary', 'Red', 'Green', 'Blue' the user could click on a cell in the Summary page and be taken to the corresponding sheet?   I'm guessing it would go into .SetCellValue?

**Comment by ggreen86** [comment]
You are welcome -- glad I can contribute to the VFP community.  For your question, I think this is a capability that is not available in the class.  Can you send me a spreadsheet that provides an example of what you are trying to do?  No promises on delivery but I would add this to the library capabilities (I already have a request for another feature that I have to incorporate).

________________________________

**Comment by nmossvfp** [comment]
Greg,

 

I am going to assume it’s ok to reply directly to the email – if I find out otherwise I will repost in the group.

See attached file:

 

When you click on any name in the ‘A’ column of the ‘Summary’ sheet which is always the first one I create, it would take you to the sheet which corresponds to that name.  Kind of like a hyperlink.  So I am tracking all of this in my table so it would be great to add to that cell – where it’s supposed to link to.   Clicking on a row would activate the corresponding sheet.   Hope that makes sense.

 

In Excel I also conditionally color the tab headers based on some condition so it would be great to specify that as well.

 

Thanks again,

-Nelson

**Comment by ggreen86** [comment]
please send to anduril58 att hotmail dot com

________________________________

**Comment by ggreen86** [comment]
I have added hyperlink functionality in Release 32 (upcoming).  The hyperlink will be to cells existing in the current workbook or to an external file.
