### ISSUE TITLE
Permissions Issue when trying to SaveWorkbookAs

### ISSUE THREAD

**Issue by eselje** [ggreen86/XLSX-Workbook-Class#30]
Not sure what's happening, but SaveWorkBookAs doesn't want to save. It returns .t. but no file appears. I'm sending it the full path name. 

```
oXLSX = CREATEOBJECT("VFPWorkBookXSLX.VFPWorkBookXSLX")
iWorkbook = oxlsx.openxlsxworkbook(cActionPriceSheet)
IF lRename
 cActionPriceSheet = ADDBS(JUSTPATH(cActionPriceSheet))+"Action Price Sheet " +  ;
   TRANSFORM(DTOC(DATE(),1),'@R 9999-99-99')+".xlsx"
ENDIF 
iResult = oxlsx.saveworkbookas(iWorkBook,cActionPriceSheet)
```

**Comment by ggreen86** [comment]
Have you traced in debug mode?   The SaveWorkbookAs() method will always return .T.; I will make changes to return the actual value from the SaveWorkbook() method.  Please add a breakpoint at the call to this method and see what the return value is.  You might need to step through the SaveWorkBook() method to see where the save is not occurring.  Please let me know the results.

________________________________

**Comment by ggreen86** [comment]
Closing issue.  No reply received since my last response to try to determine if the issue can be identified.
