### ISSUE TITLE
Suggested Changes

### ISSUE THREAD

**Issue by chadnewman** [ggreen86/XLSX-Workbook-Class#31]
Greg,
Hope you are having a great day.  Here are a couple of changes I made to your great VFP Class. 
Added to VFPxWorkbookXLSX.h to support text format for cell:
#DEFINE CELL_FORMAT_TEXT					   49	 && Text

Changed SaveTableToWorkbook method allow support for both tables and cursors
Instead of
SELECT COUNT(*) FROM &lcAlias INTO ARRAY laRowCount
Changed to:
laRowCount[1] = RECCOUNT(lcAlias)

Thanks again for the great VFP Class!

Chad

**Comment by ggreen86** [comment]
Thank you for your suggestions -- these have been incorporated for Release 32
