### ISSUE TITLE
About hidden columns

### ISSUE THREAD

**Issue by jhernancanom** [ggreen86/XLSX-Workbook-Class#32]
Hi, Greg and friends.
I have found something, a possible bug, that I want to share.

There is an XLSX file that has several sheets, as a template; the first one is empty in the template, that must be filled with data. The rest of the sheets are different reports that take data from first one according to formulas.

I use VFPxWorkbookXLSX to open the template (**OpenXlsxWorkbook**), fill the first sheet and save the result file (**SaveWorkbookAs**). I confirm that I only touch the first sheet.

The problem is that the columns that are hidden --in the other sheets in the template-- appear visible in the resulting XLSX.

If someone could give me some workaround, I'll appreciate.

HERNAN CANO
Systems Analyst

**Comment by ggreen86** [comment]
Can you provide a sample workbook and how to reproduce what you are describing.  I will look into it and let you know.

Greg

________________________________

**Comment by jhernancanom** [comment]
Yes.
[CopyToHoja1.zip](https://github.com/ggreen86/XLSX-Workbook-Class/files/5215688/CopyToHoja1.zip)

**Comment by ggreen86** [comment]
Hernan--

I am not able to reproduce a problem with the method SetSheetVisibility().  In the Demo() method I show an example of hiding a sheet using this method.  If I execute the Demo() method and create a spreadsheet and then subsequently open and save-as the workbook, I still retain the visibility setting of the 'List of Values' sheet (hidden).  Please see screen shot:

[cid:c5626ed4-2fdd-405f-b6a3-703668b79467]

Please provide sample code to reproduce the behavior you are seeing.  I am currently working/testing the next release and would like to ensure this is not a problem/bug.  Thank you.

Greg

________________________________

**Comment by ggreen86** [comment]
Release 31 and 32 Beta does not support hidden columns.  I have added this to the class which will be uploaded as Release 32 Beta 12.
