### ISSUE TITLE
About FastStrings.vcx

### ISSUE THREAD

**Issue by SeregaKR** [ggreen86/XLSX-Workbook-Class#34]
Good evening.
The class FastStrings.vcx sounds interesting and promising. Will it be available separately?
Speaking about Workbook class - will try it later this week.

**Comment by ggreen86** [comment]
I added the FastStrings library to the VFPx web page.

________________________________

**Comment by SeregaKR** [comment]
Found only here: https://www.foxite.com/archives/faststrings-library-0000475571.htm

Did not find it here: https://vfpx.github.io/projects/
