### ISSUE TITLE
Support Visual FoxPro Advanced

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#38]
Only a minor change is required to support VFP Advanced. Since VFPA returns a proper value for OS(3) (10 in Windows 10, for example), change this statement in the AddFilesToZip method:

*** 2020-02-19 DH: handle VFP Advanced
***	IF OS(3)<'6' .OR. OS(3)='6' .AND. OS(4)<'1'
	IF val(version(4)) <= 9 and (OS(3)<'6' .OR. (OS(3)='6' .AND. OS(4)<'1'))

In VFPA, VERSION(4) returns "10" so VAL(VERSION(4)) <= 9 means this isn't VFPA.

**Comment by ggreen86** [comment]
Doug--

Added your code to the method; thank you.

Greg

**Comment by jhernancanom** [comment]
Hey, Greg:
In that IF (the first) --with both clauses AND and OR--: does not need
parenthesis to run fine? I do not like character comparison (this way):
normally it depends on SET EXACT.

The second IF seems the correction............... and looks better with
respect to what I am saying.

**Comment by jhernancanom** [comment]
Hi, Greg.

As I see that you use Windows own resources for creating zip files, I want
to share with you these three URLs where there is info to make better our
utilities/libraries/classes with this respect.

It is based on adding a lot of little files. Maybe this (yours) does not
take "a lot" of files, but I think it is a core-utility that can be built
better.

By.

https://www.foxite.com/archives/zip-unzip-in-vfp9-0000422661.htm

https://comunidadvfp.blogspot.com/2014/09/programa-para-comprimir-en-zip.html

https://comunidadvfp.blogspot.com/2014/09/crear-un-zip-usando-los-recursos.html

**Comment by ggreen86** [comment]
The solution in the class is intended to be self-sufficient.  In the documentation I indicate to create your own sub-class of the class and then override the method with your own zip commands.  This way you can have your own specific implementation of the class and allow for future releases without having to re-enter your code.

________________________________

**Comment by jhernancanom** [comment]
Ok, Greg.
I'll verify your suggestion.
Thanks.
