### ISSUE TITLE
Add release date on the readme file...

### ISSUE THREAD

**Issue by mattslay** [ggreen86/XLSX-Workbook-Class#39]
May I suggest adding the *release date* on the readme page?   When these kind of projects have timestamps in their release history, I just always find that helpful.

See example below:

# Release 32
* Released 2021-02-24

Release 32 is now being released as production and no longer BETA. It has been several months now without any issues being reported.

**Comment by ggreen86** [comment]
Added to readme page -- thank you for the suggestion.

________________________________
