### ISSUE TITLE
VFPxWorkbookXLSX

### ISSUE THREAD

**Issue by Maskoer** [ggreen86/XLSX-Workbook-Class#43]
![VFPxWorkbookXLSX](https://user-images.githubusercontent.com/32405257/116806639-a9d96300-ab58-11eb-8622-93373a1aac34.jpg)

Dear Gregory Green,

How to remove the display process
 as shown in the red circle

Thanks,

Maskur

**Comment by ggreen86** [comment]
Closing issue.  The problem of the dialog is a Windows problem of ignoring the silent setting on the WinAPI call to perform the zipping of the files.
