### ISSUE TITLE
Goto Bookmark

### ISSUE THREAD

**Issue by lscheffler** [ggreen86/XLSX-Workbook-Class#44]
Hi,

I do not understand how to gather the Cell coordinates of a _bookmark_ / _named range_ I see I can manipulate it via _AddNamedRange_ / _ClearNamedRange_.    
My problem is that I have XLSX with custom defined headers where the location of (data) column header und start of data is defined via bookmark and I need to figure out this cell(s).    
EXCEL command would be GOTO(cTarget)

So what I look for is something like GetNamedRange

**Comment by ggreen86** [comment]
Unfortunately, I have not yet implemented a method for what you need.  I will add it to the list of methods for future implementation.

Greg

________________________________
From: Lutz Scheffler ***@***.***>
Sent: Friday, May 7, 2021 6:38 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Goto Bookmark (#44)


Hi,

I do not understand how to gather the Cell coordinates of a bookmark / named range I see I can manipulate it via AddNamedRange / ClearNamedRange.
My problem is that I have XLSX with custom defined headers where the location of (data) column header und start of data is defined via bookmark and I need to figure out this cell(s).
EXCEL command would be GOTO(cTarget)

So what I look for is something like GetNamedRange

**Comment by ggreen86** [comment]
It is now included in the latest beta version as GetNamedRange().  It turned out easy to implement so I just now added it.

**Comment by lscheffler** [comment]
That's great news!   
Thankyou!
