### ISSUE TITLE
Enumerate Bookmarks

### ISSUE THREAD

**Issue by lscheffler** [ggreen86/XLSX-Workbook-Class#45]
While changing my Excel handler I found, thaz az a certain point I just run through all bookmarks. 
I need to enumerate the bookmarks
Excel exposes  a collection like
````
FOR EACH loNames IN THIS.goExcel.activeWorkbook.Names
**** 

````

**Comment by ggreen86** [comment]
I have added new methods for returning the named range information.  See Release 33 beta 8.
