### ISSUE TITLE
Workbook Properties

### ISSUE THREAD

**Issue by lscheffler** [ggreen86/XLSX-Workbook-Class#48]
There is a bunch of workbook properties listed on page 8 of the doc. Is it right
- [ ] in difference to anything else they are not related to a workbook like the methods
- [ ] one can not retrieve the properties of a workbook loaded?    
- [ ] properties once set will be written on saving workbooks until changed

Just check the boxes if true.   
Thanks

**Comment by ggreen86** [comment]
The properties are read/write.  They are used when saving the content to a xlsx file.  BTW - sorry for the late reply.
