### ISSUE TITLE
About GetCellNumberFormatText()

### ISSUE THREAD

**Issue by jhernancanom** [ggreen86/XLSX-Workbook-Class#51]
Hi, Greg.
I was trying to know how was the performance of <b>.GetCellNumberFormat()</b>, and **.GetCellNumberFormatText()**, but the second drives to an error, that I am going to show you.

I have included these lines for getting the Number Format in the numeric cells:

```
if between(M.lnCol,3,6)
   M.nOldFrm1 = M.loExcel.GetCellNumberFormat    (lnWb, lnSh, M.lnRow, M.lnCol )
   M.nOldFrm2 = ''&&M.loExcel.GetCellNumberFormatText(lnWb,lnSh,M.lnRow,M.lnCol)
 **M.nOldFrm3 = M.loExcel.GetCustomNumericFormat (lnWb, M.tnFormatCode )
   
   Messagebox( ;
      '.Row: '+str(M.lnRow,2)+_CR;
     +'.Col: '+str(M.lnCol,2)+_CR;
     +'.GetCellNumberFormat    : '+tran(M.nOldFrm1)+_CR;
     +'.GetCellNumberFormatText: '+tran(M.nOldFrm2)+_CR;
     +'',0,'Versión R'+tran(M.loExcel.ExcelXlsxRelease), 5*1000 )
endif
```
If I get out **''&&** de M.nOldFrm2, the function GetCellNumberFormatText() shows an error message, that we can see in image 01.
If I run the program again, I see (image 02) that the program --for row 1-- shows from col 3 to 6, and ok; but in row 2 shows col 3 ok, col 4 ok, but for col 5 when M.nOldFrm2 = M.loExcel **.GetCellNumberFormatText(lnWb,lnSh,M.lnRow,M.lnCol),** rises the error in image 03.

I decided to suspend and made some investigation. In image 3a we see that the line with the error is lcFormatCode = xl_cellxfs.formatcode, where the class tries to get the format number of a cell. And in image 3b that the method is GetCellNumberFormatText().
I look if xl_cellxfs has the field formatcode, and if find (1) xl_cellxfs has no the field formatcode; and (2) xl_numfmts does have the field formatcode; image 3c.

((images inside .doc))

Thanks for sharing this library.
[Mensaje-About GetCellNumberFormatText().docx](https://github.com/ggreen86/XLSX-Workbook-Class/files/6551860/Mensaje-About.GetCellNumberFormatText.docx)
[About filling a template in R33-beta8.zip](https://github.com/ggreen86/XLSX-Workbook-Class/files/6551862/About.filling.a.template.in.R33-beta8.zip)

**Comment by ggreen86** [comment]
You are missing some screen shots I believe.  Please provide an example PRG that will reproduce your error so that I can debug and fix.

**Comment by jhernancanom** [comment]
Sorry, Greg. 
Here are the right .DOCx, and also the images.

[Mensaje-About GetCellNumberFormatText().docx](https://github.com/ggreen86/XLSX-Workbook-Class/files/6810375/Mensaje-About.GetCellNumberFormatText.docx)
[imagenes-GetCellNumberFormatText.zip](https://github.com/ggreen86/XLSX-Workbook-Class/files/6810394/imagenes-GetCellNumberFormatText.zip)

**Comment by ggreen86** [comment]
Thank you -- will look into the problem.

________________________________

**Comment by ggreen86** [comment]
Sorry for the VERY late reply -- this was corrected sometime back.   The GetCellNumberFormat() method is now returning the cell format style Id.  The method GetCellNumberFormatText() will now return the numeric format from the defined style.
