### ISSUE TITLE
GetSheetHidden and GetRowHidden Methods

### ISSUE THREAD

**Issue by veladaltura** [ggreen86/XLSX-Workbook-Class#52]
Hi Green. I noticed that the library has the method GetColumnHidden.
Is it possible to implement the following methods in the future?
- GetSheetHidden
- GetRowHidden

Thank you for all. Best regards.

Riccardo

**Comment by ggreen86** [comment]
I will add to my "To Do" list.

________________________________
From: veladaltura ***@***.***>
Sent: Thursday, May 27, 2021 5:02 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] GetSheetHidden and GetRowHidden Methods (#52)


Hi Green. I noticed that the library has the method GetColumnHidden.
Is it possible to implement the following methods in the future?

  *   GetSheetHidden
  *   GetRowHidden

Thank you for all. Best regards.

Riccardo

**Comment by veladaltura** [comment]
Many thanks

**Comment by msueping** [comment]
And let's not forget about SetRowHidden? There's a SetSheetVisibility that I assume corresponds with the GetSheetHidden mentioned above (although the names should be made to be similar).

**Comment by ggreen86** [comment]
See Release 33, beta 10.  Methods SetRowHidden() and GetRowHidden() have been added.  The method SetSheetVisibility() does the hidden setting; I do not want to change its name due to others now possibly using this method and it would break their code.
