### ISSUE TITLE
Ignore ampersand in sheet name

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#55]
An ampersand in a sheet name is invalid, so I updated CheckSheetName as follows:

```
*** DH 2021-06-10: handle "&" too
*lcSheetName = CHRTRAN(tcSheetName, ":\/?*", "_____")
lcSheetName = CHRTRAN(tcSheetName, ":\/?*&", "______")
```

**Comment by ggreen86** [comment]
Doug--

I just opened Excel 2016 and created a test workbook with the sheet name using a & symbol:

[cid:b517b597-0738-45fe-a7f6-d3a0caae54e2]

I saved the workbook; closed Excel and then reopened the workbook -- it still has the & with no errors.  I believe when I was coding the exclusion list, I tried all the special characters in the sheet name directly in Excel to determine those that were invalid.

Greg

________________________________
From: Doug Hennig ***@***.***>
Sent: Thursday, June 10, 2021 3:07 PM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Ignore ampersand in sheet name (#55)


An ampersand in a sheet name is invalid, so I updated CheckSheetName as follows:

*** DH 2021-06-10: handle "&" too
lcSheetName = CHRTRAN(tcSheetName, ":/?", "")
lcSheetName = CHRTRAN(tcSheetName, ":/?*&", "_")

**Comment by DougHennig** [comment]
I created the attached document using SaveGridToWorkbookEx with "A & B" specfied as the sheet name. Excel says the file is corrupted and won't open it. With the change I noted above, the document opens correctly.

[A & B.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/6634218/A.B.xlsx)

**Comment by ggreen86** [comment]
Doug--

I see the error -- the & is not getting encoded for the sheet name as shown:

[cid:5ce2f196-c544-4ff9-b140-773d16ed6b5f]

I will look into this for a fix.

Greg

________________________________

**Comment by DougHennig** [comment]
My mistake: I was using R33 Beta 6 not Beta 8. Sorry about that!
