### ISSUE TITLE
Delete rows

### ISSUE THREAD

**Issue by gturriziani** [ggreen86/XLSX-Workbook-Class#58]
Hi, the class is fantastic, but there is a way to delete a row?

**Comment by ggreen86** [comment]
Hmm,  seems I have missed adding this method.  It is a basic method, but I have not had to use it so I missed adding it.  I will try to add this method over the next few days as my time permits.  It should not be too hard to implement.  Will add DeleteRow(), DeleteColumn(), and DeleteCell() methods.

________________________________
From: gturriziani ***@***.***>
Sent: Tuesday, July 6, 2021 6:49 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Delete rows (#58)


Hi, the class is fantastic, but there is a way to delete a row?

**Comment by gturriziani** [comment]
Thanks, very kind of you.

**Comment by ggreen86** [comment]
See Release 33 beta 10 -- these methods have been added (see Release Notes)

**Comment by gturriziani** [comment]
Thank you very much!

**Comment by ggreen86** [comment]
You are welcome.

________________________________
