### ISSUE TITLE
Handle Z format in GetGridColumnFormat

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#61]
GetGridColumnFormat doesn't handle "Z" (display zero as blank) in the format for a numeric column. I would change this myself but I'm not sure how NumFmtsIndex works.

**Comment by ggreen86** [comment]
Doug--

Can you provide a column format example of the z-format usage?  Thank you.

Greg

________________________________
From: Doug Hennig ***@***.***>
Sent: Tuesday, July 20, 2021 10:29 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Handle Z format in GetGridColumnFormat (#61)


GetGridColumnFormat doesn't handle "Z" (display zero as blank) in the format for a numeric column. I would change this myself but I'm not sure how NumFmtsIndex works.

**Comment by DougHennig** [comment]
Set Format to Z and InputMask to 999,999.99. Zeros will appear as blank in the grid.

**Comment by ggreen86** [comment]
Doug--

I have added the ability to hide zero values (not display) in the cell, but it is shown in the edit textbox.  This is done by a new parameter being added to the methods for setting the ShowZeros property for the sheet during the workbook create for a grid or a table.  There is also a method to setting it directly.  See the Release Notes for R39 Beta 13.
