### ISSUE TITLE
GetCellValue

### ISSUE THREAD

**Issue by tavocrochenci** [ggreen86/XLSX-Workbook-Class#63]
Hi, Greg and friends.
I'm having trouble getting the value of the cell when it contains a formula. Is it possible to get the value? I am not interested in obtaining the formula, only the value of it.

![image](https://user-images.githubusercontent.com/92101808/136395814-ff0ff79c-40a7-4e8b-99e5-1a7c653242f6.png)

Greetings!

**Comment by ggreen86** [comment]
The class does not store the value when the cell has a formula.
