### ISSUE TITLE
Xlsx file is invalid if first row is not text

### ISSUE THREAD

**Issue by Harbour-J** [ggreen86/XLSX-Workbook-Class#69]
...
loXL.SetCellValue(lnWb, lnSheet, 1, 1, 'Header')
loXL.SetCellValue(lnWb, lnSheet, 2, 1, 2)
...
works fine to create a 2-cell spreadsheet.
...
loXL.SetCellValue(lnWb, lnSheet, 1, 1, 1)
loXL.SetCellValue(lnWb, lnSheet, 2, 1, 2)
...
gives as error message from Excel "We found a problem with some content in ..."

**Comment by ggreen86** [comment]
Hello--

I cannot reproduce the error that you are seeing.  Below is my code:

Test 1:

lnWb = loExcel.CreateWorkbook("FirstRowTest.xlsx")
lnSh = loExcel.AddSheet(lnWb, "Sheet1")

loExcel.SetCellValue(lnWb, lnSh, 2, 1, 20)  && Sheet1, Row 2, column A
loExcel.SaveWorkbook(lnWb)

Test 2:

lnWb = loExcel.CreateWorkbook("FirstRowTest.xlsx")
lnSh = loExcel.AddSheet(lnWb, "Sheet1")

loExcel.SetCellValue(lnWb, lnSh, 2, 2, 20)   && Sheet1, Row 2, column B
loExcel.SaveWorkbook(lnWb)

Test 3:

lnWb = loExcel.CreateWorkbook("FirstRowTest.xlsx")
lnSh = loExcel.AddSheet(lnWb, "Sheet1")
lnSh = loExcel.AddSheet(lnWb, "Sheet2")

loExcel.SetCellValue(lnWb, lnSh, 2, 2, 20)   && Sheet2, Row 2, column B
loExcel.SaveWorkbook(lnWb)

In the above tests, I am able to open the spreadsheet successfully using Excel 2016.  If you are still experiencing the problem, please send me the spreadsheet file that is created by your program code and the spreadsheet file that is opened by Excel with you applying the fix.  I believe that Excel 2010 might not work as another user has experienced issues trying to open spreadsheets.  If you are also using Excel 2010 (or any of your users will be) please send me the two files so that I can analyze the difference between the generated file and the Excel corrected file.  Hopefully, I can identify the underlying issue with Excel 2010.

Thank you.

Greg
________________________________
From: Harbour-J ***@***.***>
Sent: Thursday, August 4, 2022 10:45 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Xlsx file is invalid if first row is not text (Issue #69)


...
loXL.SetCellValue(lnWb, lnSheet, 1, 1, 'Header')
loXL.SetCellValue(lnWb, lnSheet, 2, 1, 2)
...
works fine to create a 2-cell spreadsheet.
...
loXL.SetCellValue(lnWb, lnSheet, 1, 1, 1)
loXL.SetCellValue(lnWb, lnSheet, 2, 1, 2)
...
gives as error message from Excel "We found a problem with some content in ..."

**Comment by Harbour-J** [comment]
Hi, Greg
It's not 2010 - Microsoft® Excel® for Microsoft 365 MSO (Version 2205 Build 16.0.15225.20292) 32-bit

Sorry, I think I confused you by using 1 & 2 as my example numbers as well as the row numbers. Here's some clearer code.

loXL = CREATEOBJECT('VFPxWorkbookXLSX')
lnWb = loXL.CreateWorkbook('good.xlsx')
lnSh = loXL.AddSheet(lnWb, "Sheet1")
loXL.SetCellValue(lnWb, lnSh, 1, 1, 'Data')	&& A1
loXL.SetCellValue(lnWb, lnSh, 2, 1, 99)		&& A2
loXL.SaveWorkbook(lnWb)
ShellEx('good.xlsx')

lnWb = loXL.CreateWorkbook('bad.xlsx')
lnSh = loXL.AddSheet(lnWb, "Sheet1")
*loXL.SetCellValue(lnWb, lnSh, 1, 1, 'Data')
loXL.SetCellValue(lnWb, lnSh, 1, 1, 123)	&& A1
loXL.SetCellValue(lnWb, lnSh, 2, 1, 99)	&& A2
loXL.SaveWorkbook(lnWb)
ShellEx('bad.xlsx')

This fails to open bad.xlsx. Curiously, if I uncomment the commented line it works. Also, if I change it to write to A1 and B1, it fails in the same way. Files attached.

Many thanks

John

[bad.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/9269308/bad.xlsx)
[good.xlsx](https://github.com/ggreen86/XLSX-Workbook-Class/files/9269309/good.xlsx)

**Comment by Harbour-J** [comment]
Hi,

Were you able to open the bad.xlsx that I sent you?

This is the “log file listing repairs” that Excel creates:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns=http://schemas.openxmlformats.org/spreadsheetml/2006/main>
<logFileName>error153160_01.xml</logFileName>
<summary>Errors were detected in file 'C:\dev\Sm\bad - Copy.xlsx'</summary>
<removedRecords>
<removedRecord>
Removed Records: Worksheet properties from /xl/workbook.xml part (Workbook)
</removedRecord>
</removedRecords>
</recoveryLog>

The “fixed” s/s (attached) is empty, to the untrained eye at least.

Regards

John

P.S. I’m in the UK where it’s late Friday p.m. Am about to disappear till Monday.

**Comment by ggreen86** [comment]
John--

I found the problem.  Your 'bad.xlxs' file is missing the internal file sheet1.xml which defines the sheet values.  Not sure why it is missing.  Please try the below code and let me know the results.  Also, make sure you are using the most current version of the class from VFPx.

loExcel = NEWOBJECT("VFPxWorkbookXLSX", "..\VFPxWorkbookXLSX.vcx")
lnWb = loExcel.CreateWorkbook("FirstRowTest.xlsx")

lnSh = loExcel.AddSheet(lnWb, "Sheet1")
*loExcel.SetCellValue(lnWb, lnSh, 1, 1, 'Data')
loExcel.SetCellValue(lnWb, lnSh, 1, 1, 123) && A1
loExcel.SetCellValue(lnWb, lnSh, 2, 1, 99) && A2

loExcel.SaveWorkbook(lnWb)


Greg
________________________________

**Comment by Harbour-J** [comment]
Hi, Greg

I’m running R32. I’ve recopied the .vcx, .vct and .h files from the .zip just in case.

I ran the code as written, except I needed "..\ClassLib\VFPxWorkbookXLSX.vcx".

***@***.***

John

**Comment by ggreen86** [comment]
John--

Just to clarify, did the code that I sent work for you and create a correct workbook file?  Thank you.

Greg
________________________________

**Comment by Harbour-J** [comment]
Sorry to be unclear. No it didn’t. My email contained a snip of the "We found a problem with some content in FirstRowTest.xlsx …" message, which presumably didn’t reach you.

John

**Comment by Harbour-J** [comment]
Hmm. My WriteSheetXMLs is only 688 lines long, so your reference to line 748 is interesting!

I’ve now installed R34 beta 4 and my problem is fixed.

Thanks.

John

**Comment by Harbour-J** [comment]
Hi, Greg

I just spotted this in the Release 33 Beta notes:

“I have just added Beta 7 which fixes a couple of bugs that was found. In particular, I found a bug in the previous releases that occurred when no text was assigned to any cells (only numeric values). The save method would remove the strings.xml from being written, but in doing so, the record pointer in an internal cursor would get moved causing the skipping of writing the first sheet.xml. If only one sheet was added, then the resulting workbook would be in error as well.”

Sounds like my problem.

John

P.S. My code failed in R34 beta 4, due to SetCellAlignment() stomping on the work area. I’ve worked around it by changing
luData = EVALUATE(FIELD(lnCol))
to
luData = EVALUATE(lcCursor + '.' + FIELD(lnCol, lcCursor))
but I do believe that class methods should restore the original work area before returning.

**Comment by ggreen86** [comment]
John--

Where is the code line that you referenced below?  I did a search and do not find it in the class library.

Greg
________________________________

**Comment by Harbour-J** [comment]
Hi, Greg

That’s my code, not yours.

luData = EVALUATE(FIELD(lnCol))
was written on the (dangerous) assumption that within a tight SCAN loop through a cursor the work area is stable. It was until I moved to R34 beta 4. But in that release, SetCellAlignment() changes the work area.

SELECT workbook FROM xl_cells WHERE workbook = tnWB AND cellxfs = lnCellXfsId INTO CURSOR xl_temp
…
USE IN SELECT('xl_temp')

is what’s doing this. This is a philosophical question. I would argue that any externally exposed method in a class library should always preserve the work area. I do this with a simple
lnSelect = SELECT()
…
SELECT (lnSelect)
RETURN …

It’s a PITA if the calling code has to constantly defend against the rug being pulled from under it.

Regards

John

**Comment by Harbour-J** [comment]
Hi Greg

The program below creates the attached spreadsheet. There seem to be a few issues with DateTime formatting.

Regards

John

P.S. Let me know if you’d prefer me to put this on GitHub as a new query.

*

* DateTest.prg

*

LOCAL loXL, lnWb, lnSh, lnStyle, lcFormat, lnFormat, lnRow



#INCLUDE VFPxWorkbookXLSX.h



loXL = CREATEOBJECT('VFPxWorkbookXLSX')

lnWb = loXL.CreateWorkbook('DateTest.xlsx')

lnSh = loXL.AddSheet(lnWb, 'Sheet1')



loXL.SetColumnWidth(lnWb, lnSh, 1, 15)

loXL.SetColumnWidth(lnWb, lnSh, 2, 40)

loXL.SetColumnWidth(lnWb, lnSh, 3, 75)



loXL.SetCellValue(lnWb, lnSh, 1, 1, 'Value')

loXL.SetCellValue(lnWb, lnSh, 1, 2, 'Format')

loXL.SetCellValue(lnWb, lnSh, 1, 3, 'Notes')



lnRow = 2

loXL.SetCellValue(lnWb, lnSh, 2, 1, 44015.338889)

lnStyle = loXL.CreateFormatStyle(lnWb)

lcFormat = '###0.0"kg";[Red]-###0.0"kg";"";General'

lnFormat = loXL.AddNumericFormat(lnWb, lcFormat)

loXL.AddStyleNumericFormat(lnWb, lnStyle, lnFormat)

loXL.SetCellStyleRange(lnWb, lnSh, lnRow, 1, lnRow, 1, lnStyle)

loXL.SetCellValue(lnWb, lnSh, lnRow, 2, lcFormat)

loXL.SetCellValue(lnWb, lnSh, lnRow, 3, 'A custom numeric format. Works perfectly.')



lnRow = 3

loXL.SetCellValue(lnWb, lnSh, lnRow, 1, 44015.338889)

lnStyle = loXL.CreateFormatStyle(lnWb)

lcFormat = 'dd mmm yy hh:mm'

lnFormat = loXL.AddNumericFormat(lnWb, lcFormat)

loXL.AddStyleNumericFormat(lnWb, lnStyle, lnFormat)

loXL.SetCellStyleRange(lnWb, lnSh, lnRow, 1, lnRow, 1, lnStyle)

loXL.SetCellValue(lnWb, lnSh, lnRow, 2, lcFormat)

loXL.SetCellValue(lnWb, lnSh, lnRow, 3, 'A custom datetime format. Works when used manually in excel, but not in code.')



lnRow = 4

loXL.SetCellValue(lnWb, lnSh, lnRow, 1, 44015.338889)

lnStyle = loXL.CreateFormatStyle(lnWb)

lcFormat = 'dd mmm yy'

lnFormat = loXL.AddNumericFormat(lnWb, lcFormat)

loXL.AddStyleNumericFormat(lnWb, lnStyle, lnFormat)

loXL.SetCellStyleRange(lnWb, lnSh, lnRow, 1, lnRow, 1, lnStyle)

loXL.SetCellValue(lnWb, lnSh, lnRow, 2, lcFormat)

loXL.SetCellValue(lnWb, lnSh, lnRow, 3, 'A custom date format. Works when used manually in excel, but not in code.')



lnRow = 5

loXL.SetCellValue(lnWb, lnSh, lnRow, 1, 44015.338889)

lnStyle = loXL.CreateFormatStyle(lnWb)

lcFormat = 'CELL_FORMAT_DATETIME_DDMMMYYYY_TT24'

loXL.AddStyleNumericFormat(lnWb, lnStyle, CELL_FORMAT_DATETIME_DDMMMYYYY_TT24)

loXL.SetCellStyleRange(lnWb, lnSh, lnRow, 1, lnRow, 1, lnStyle)

loXL.SetCellValue(lnWb, lnSh, lnRow, 2, lcFormat)

loXL.SetCellValue(lnWb, lnSh, lnRow, 3, "Not sure what's happened to the TT24 part of this, or why MMM doesn't show Jul.")



lnRow = 6

loXL.SetCellValue(lnWb, lnSh, lnRow, 1, 44015.338889)

lnStyle = loXL.CreateFormatStyle(lnWb)

lcFormat = 'CELL_FORMAT_DATETIME_MDYYHMM'

loXL.AddStyleNumericFormat(lnWb, lnStyle, CELL_FORMAT_DATETIME_MDYYHMM)

loXL.SetCellStyleRange(lnWb, lnSh, lnRow, 1, lnRow, 1, lnStyle)

loXL.SetCellValue(lnWb, lnSh, lnRow, 2, lcFormat)

loXL.SetCellValue(lnWb, lnSh, lnRow, 3, "Correct, except that YY implies 20 not 2020.")



lnRow = 7

loXL.SetCellValue(lnWb, lnSh, lnRow, 1, 44015.338889)

lnStyle = loXL.CreateFormatStyle(lnWb)

lcFormat = 'CELL_FORMAT_DATE_DMMMYY'

loXL.AddStyleNumericFormat(lnWb, lnStyle, CELL_FORMAT_DATE_DMMMYY)

loXL.SetCellStyleRange(lnWb, lnSh, lnRow, 1, lnRow, 1, lnStyle)

loXL.SetCellValue(lnWb, lnSh, lnRow, 2, lcFormat)

loXL.SetCellValue(lnWb, lnSh, lnRow, 3, "I can live with this, though I don't like the dashes.")



lnRow = 8

loXL.SetCellValue(lnWb, lnSh, lnRow, 1, 44015.338889)

lnStyle = loXL.CreateFormatStyle(lnWb)

lcFormat = 'CELL_FORMAT_DATETIME_MMMDDYYYY_TT24'

loXL.AddStyleNumericFormat(lnWb, lnStyle, CELL_FORMAT_DATETIME_MMMDDYYYY_TT24)

loXL.SetCellStyleRange(lnWb, lnSh, lnRow, 1, lnRow, 1, lnStyle)

loXL.SetCellValue(lnWb, lnSh, lnRow, 2, lcFormat)

loXL.SetCellValue(lnWb, lnSh, lnRow, 3, "Well, that didn't work!")



lnRow = 9

lnStyle = loXL.CreateFormatStyle(lnWb)

loXL.SetCellValue(lnWb, lnSh, lnRow, 1, 44015.338889)

loXL.SetCellValue(lnWb, lnSh, lnRow, 2, "CELL_FORMAT_DATE_DMMMYYHMM")

loXL.SetCellValue(lnWb, lnSh, lnRow, 3, "This would do, but it doesn't exist.")



loXL.SaveWorkbook(lnWb)



ShellEx('DateTest.xlsx')

**Comment by ggreen86** [comment]
John--

Yes, please open a new issue to track this.  This way others can find a similar issue if they have it as well.  In the meantime, I will check into this.  Thank you.

Greg
________________________________

**Comment by ggreen86** [comment]
This issue has been fixed.
