### ISSUE TITLE
Defined Names

### ISSUE THREAD

**Issue by zulqasar** [ggreen86/XLSX-Workbook-Class#72]
localSheetId for defined names should be based on 0 index. This means localSheetId will be lnSh - 1.

Code on line 74 in writeWorkbookXml method should be
```
*-- line 73
if xl_namerange.scope = SCOPE_SH_NAMED_RANGE
    *-- line 74 should be as follows
    write(lhFile, ' localSheetId="' + transform(xl_namerange.sheet - 1) + '"')
```

I don't know what impact it will have if we have deleted sheets in between. Need to test it out.

**Comment by ggreen86** [comment]
Hello--

Thank you for adding this issue.  I have incorporated this into the base class which will be released in the future as the next beta.

Greg
________________________________
