### ISSUE TITLE
Question about formatting for green bar

### ISSUE THREAD

**Issue by nmossvfp** [ggreen86/XLSX-Workbook-Class#84]
The sample below is taken from the DEMO mode code.

*=MOD(ROW(A2),2)=1	
*!*	* Add AVERAGE(), MAX(), & MIN() formula to columns
*!*	this.SetCellFormula(lnWb, lnSh2, 16, 3, "=AVERAGE(C10:C15)")
*!*	this.SetCellFormula(lnWb, lnSh2, 16, 4, "=MAX(D10:D15)")
*!*	this.SetCellFormula(lnWb, lnSh2, 16, 5, "=MIN(E10:E15)")

I have been trying but so far have been unsuccesful to create a "Green Bar paper" like effect on a worksheet using code.

Using the conventional formaula [=MOD(ROW(A2),2)=1]
I would want to alternate light green such as an RGB(226,239,218) fill for all odd rows of a sheet except the header row.

Can I use SetCellFormula to achieve the desired effect?

Thanks

**Comment by ggreen86** [comment]
The SetCellFormula method only sets the formula for the cell; it cannot set the format also.  You would have to define a format style with the background effect that you want and then apply to every other row/cells.  There is not currently any support for dynamic formatting or table formatting.

**Comment by nmossvfp** [comment]
Ok.   Got it.   Thanks.
