### ISSUE TITLE
AddAutoFilter in grid export all columns 

### ISSUE THREAD

**Issue by flexsoluciones** [ggreen86/XLSX-Workbook-Class#86]
How to add filter when exporting from a grid thanks

**Comment by ggreen86** [comment]
There is not a function to provide for assigning Auto Filters during the export of a grid.

From: flexsoluciones ***@***.***>
Sent: Monday, May 29, 2023 11:36 PM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] AddAutoFilter in grid export all columns (Issue #86)


How to add filter when exporting from a grid thanks

**Comment by ggreen86** [comment]
This feature has been added to the method SaveGridToWorkbookEx() in Release 39.
