### ISSUE TITLE
wrong parameter name in DeleteColomn method

### ISSUE THREAD

**Issue by RezaUzer** [ggreen86/XLSX-Workbook-Class#97]
Dear Greg,

Please correct the code for method DeleteColumn.
tnSheet in LPARAMETERS line and tnSh in other lines.
thank you very much.

LPARAMETERS tnWB, tnSheet, tnCol
DELETE FOR xl_cells.workbook = tnWB .AND. xl_cells.sheet = tnSh .AND. xl_cells.cellcol = tnCol IN xl_cells
REPLACE xl_cells.cellcol WITH xl_cells.cellcol - 1 FOR xl_cells.workbook = tnWB .AND. xl_cells.sheet = tnSh .AND. xl_cells.cellcol > tnCol IN xl_cells

**Comment by ggreen86** [comment]
Thank you for letting me know -- I have corrected this issue in R39 Beta 12.
