### ISSUE TITLE
Property value is out of bound

### ISSUE THREAD

**Issue by Esox61** [ggreen86/XLSX-Workbook-Class#98]
Hi Greg!
I wanted to try your program, but at the Newobject line it says: "Property value is out of bound". I tried several versions, all with the same result. Can you tell me what the solution is? 

Thx:
         Esox

**Comment by ggreen86** [comment]
What are you doing to get this message?  Please provide me a sample of your code that produces this problem.

Greg

From: Esox61 ***@***.***>
Sent: Friday, August 25, 2023 11:27 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Property value is out of bound (Issue #98)


Hi Greg!
I wanted to try your program, but at the Newobject line it says: "Property value is out of bound". I tried several versions, all with the same result. Can you tell me what the solution is?

Thx:
Esox

**Comment by ggreen86** [comment]
I tried the same program and it successfully opens the selected workbook with no errors and resaves it; note that I made a change to the relative path of the vcx (see below).  Can you please re-run on your PC and select ‘Suspend’.  Then open the Debugger and show me the program step that it has stopped at and the local variable values via a screen shot.

***@***.***

Greg

**Comment by Esox61** [comment]
>I made a change to the relative path of the vcx (see below).
Sorry, but see what?

![Clipboard01](https://github.com/ggreen86/XLSX-Workbook-Class/assets/58699655/a1473a97-0cb1-448f-bff2-059587fefc87)
Is that what you thought?

**Comment by ggreen86** [comment]
I think you need to change the line:

       goExcel = NEWOBJECT("VFPxWorkbookXLSX", "VFPxWorkbookXLSX.vcx")

To

       goExcel = NEWOBJECT("VFPxWorkbookXLSX", "..\VFPxWorkbookXLSX.vcx")

Greg

**Comment by Esox61** [comment]
did it, but the same error message came up :(
![Clipboard01](https://github.com/ggreen86/XLSX-Workbook-Class/assets/58699655/6d344b2a-a1de-4c46-bd39-7493c843b10f)

**Comment by ggreen86** [comment]
Not sure what your problem exactly is.  I still think you are having a problem with the paths.  Try this at the command line:

SET PATH TO <where you have the VFPxWorkbookXLSX.vcx located>
goExcel = NEWOBJECT("VFPxWorkbookXLSX", "VFPxWorkbookXLSX.vcx")

From your screen shot below, I think “<where you have the VFPxWorkbookXLSX.vcx located>” should be “c:\fox”

This should create an object goExcel that can be viewed in the Debugger.  Also, you should have many cursors created that start with ‘xl_’.  If this works, then at the command line try:

lnWb = goExcel.OpenXlsxWorkbook(“c:\fox\program demos\proba.xlsx”)

This will then open the workbook and fill the “xl_” cursors with the workbook information (note that the workbook must exist).

If this works, then try at the command line:

goExcel.SaveWorkbookAs(lnWb, "c:\fox\program demos\probaCopy.xlsx")

This will then save the opened workbook as a copy.

Greg

**Comment by Esox61** [comment]
I did what you described. I typed in the command "set path to "c:\fox". Here is the VFPxWorkbookXLSX.vcx, which the program finds. However, it cannot create the goExcelt object, instead it gives the usual error message: Property valueis out of bounds. :(

**Comment by Esox61** [comment]
I tried  it on other PC, the result is same :( Which version did you try it? I use Vfp 8.

**Comment by Esox61** [comment]
I tried to open the TestForm form: 
![Clipboard02](https://github.com/ggreen86/XLSX-Workbook-Class/assets/58699655/7e9ef68e-1b05-48a0-8d9c-c8a476b00969)
Does this help you identify the error?

**Comment by ggreen86** [comment]
Hello—

I am able to open the form without an error.  When I first opened it, it prompted me for the location of the workbook class – I selected the location and then the form opened as shown:

***@***.***

Greg

**Comment by ggreen86** [comment]
I think the version of VFP is your problem.  I am using VFP9 SP2.  I believe there are features in version 9 that are being used that are not available in version 8.

**Comment by Esox61** [comment]
Thanks for your answers!  I'm very sad! :(

**Comment by Woody-Soft** [comment]
Hi Esox61,

VFP9 is now already 19 years old. Nineteen! Seems to me that there would have been really enuf time to recompile your stuff.
Come on, give it a try!  😊

(If you really don't have a VFP9 at the office, there are several downloads floating around the Internet, and MS doesn't care about VFP)

With kind regards from Bavaria

Jürgen Wondzinski
Visual FoxPro<http://www.msdn.com/vfoxpro> Evangelist
Microsoft "Most Valuable Professional<http://mvp.microsoft.com/de-de/overview.aspx>" from 1996 to 2009, "Servoy Valued Professional<http://www.servoy.com/>“ 2011
My XING Profile<https://www.xing.com/profile/Juergen_Wondzinski>, and LinkedIn<http://www.linkedin.com/in/wondzinski> and Facebook<http://www.facebook.com/juergen.wondzinski> and Twitter<http://www.twitter.com/wondzinski> and…..
GCS d+ s:+ a+++ C++ !U P--- L E? W++ N++ o-- K--? w+++ O? !M--? V-- PS PE !Y? !PGP t 5 X R tv- b DI+ D? G e++ h-- r+++ y+++




Von: Esox61 ***@***.***>
Gesendet: Montag, 28. August 2023 15:24
An: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [ggreen86/XLSX-Workbook-Class] Property value is out of bound (Issue #98)


Thanks for your answers! I'm very sad! :(

**Comment by Esox61** [comment]
Hi Jürgen!

Yes, you are right, Vfp9 has been around for a long time. I heard at the time that there were compatibility problems between Vfp8 and Vfp9, so I didn't dare to switch. (Anyway, yesterday I installed Vfp9 as a trial, tried VFPxWorkbookXLSX.vcx and it runs under Vfp9 on my machine.)

I wish you all the best: 
                                      Esox61

**Comment by jhernancanom** [comment]
@Esox61
And have not been solved?
Please tell me what are them for me to try'em.
Thanks....

**Comment by Esox61** [comment]
@jhernancanom
Greg tried to help a lot and finally the solution is to run this vcx only under Vfp9.
